import React, { createContext, useContext, useState } from 'react';
import { legal, type LegalContent } from '../content/legal';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  translations: typeof translations[Language];
  /**
   * Textos legais. Vivem em `src/content/legal/` e não aqui: este arquivo já
   * carrega navegação, catálogo de produtos e links de pagamento, e três
   * documentos jurídicos o tornariam impossível de manter.
   */
  legal: LegalContent;
}

const translations = {
  pt: {
    greeting: "Olá, me chamo",
    description: "Um desenvolvedor com experiência no back-end e criação de serviços e bots robustos. Atualmente sou Auxiliar de T.I, focado em criar soluções limpas e modernas.",
    availableForWork: "Disponível para novos projetos",
    cleanCode: "Código Limpo",
    cleanCodeDesc: "Escrevendo soluções manuteníveis, escaláveis e eficientes.",
    modernUI: "UI/UX Moderno",
    modernUIDesc: "Criando experiências de usuário bonitas e intuitivas.",
    responsive: "Responsivo",
    responsiveDesc: "Execução perfeita em todos os dispositivos e tamanhos de tela.",
    viewWork: "Ver Meu Trabalho",
    getInTouch: "Entre em Contato",
    portfolio: "Portfólio",
    resume: "Currículo",
    products: "Produtos",
    contact: "Contato",
    features: "Funcionalidades",
    todoList: "Lista de Tarefas",
    financeManager: "Finanças",
    calculator: "Calculadora",
    urlShortener: "Encurtador de URL",
    roulette: "Roleta",
    passwordGenerator: "Gerador de Senhas",
    pwgenTitle: "Gerador de Senhas",
    pwgenSubtitle: "Gere senhas e frases-senha fortes. Nada é enviado a servidores.",
    pwgenTabPassword: "Senha",
    pwgenTabPassphrase: "Frase-senha",
    pwgenModeRandom: "Aleatória",
    pwgenModeWords: "Com palavras",
    pwgenLength: "Comprimento",
    pwgenLengthHint: "Valor entre 5 e 128.",
    pwgenUppercase: "Maiúsculas (A-Z)",
    pwgenLowercase: "Minúsculas (a-z)",
    pwgenNumbers: "Números (0-9)",
    pwgenSymbols: "Especiais (!@#$%&*)",
    pwgenMinNumbers: "Mín. de números",
    pwgenMinSymbols: "Mín. de especiais",
    pwgenDigitRun: "Sequência de números",
    pwgenSymbolStyle: "Estilo de símbolos",
    pwgenSymbolNone: "Nenhum",
    pwgenSymbolSeparator: "Separador entre palavras",
    pwgenSymbolWrapped: "Separador + envolvente",
    pwgenMixedCase: "Capitalização aleatória",
    pwgenWordCount: "Número de palavras",
    pwgenSeparator: "Separador",
    pwgenSepDash: "Hífen ( - )",
    pwgenSepDot: "Ponto ( . )",
    pwgenSepUnderscore: "Sublinhado ( _ )",
    pwgenSepSpace: "Espaço",
    pwgenSepNone: "Nenhum",
    pwgenCapitalize: "Capitalizar palavras",
    pwgenIncludeNumber: "Incluir número",
    pwgenOptions: "Opções",
    pwgenHistory: "Histórico",
    pwgenHistoryEmpty: "Nenhuma senha gerada ainda.",
    pwgenClearHistory: "Limpar histórico",
    pwgenCopy: "Copiar",
    pwgenCopied: "Copiado!",
    pwgenRegenerate: "Gerar novamente",
    pwgenShow: "Mostrar",
    pwgenHide: "Ocultar",
    pwgenNoCharset: "Selecione ao menos um tipo de caractere.",
    pwgenMinError: "A soma dos mínimos não pode passar do comprimento.",
    login: "Login",
    register: "Registrar",
    logout: "Sair",
    rights: "Todos os direitos reservados.",
    contactP: "Contate-me",
    connect: "Fale Comigo",
    name: "Nome",
    message: "Mensagem",
    productsAndServices: "Produtos e Serviços",
    learnMore: "Saiba Mais",
    buyNow: "Comprar",
    sendMessage: "Enviar Mensagem",
    viewProject: "Ver projeto",
    productList: [
      { id: 1, name: "Conhecer os bots do discord", description: "Um bot completamente personálizavel, focado em moderação e segurança.", image: "https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/4088758/cover_image/retina_1708x683/cover-how-to-make-a-discord-bot-0afaa27d630de8c4b711f5cd5abbf01f.png", link: "/plans" },
      { id: 2, name: "FiveM Mod Manager", description: "Gerencie seus mods do FiveM com apenas um clique. Instale, ative e desative mods de som, RPF e Citizens com backup automático e otimizações de desempenho.", image: "https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/270123807/original/2e13089eeeef09bbb2a04d238dce1f419b5a7268/install-gta-fivem-server-with-qbcore-linux-or-windows.png", link: "/fmm" }
    ],
    downloadPDF: "Baixar PDF",
    personalInfo: "Dados Pessoais",
    phone: "(62) 98608-9609",
    email: "davi@davimf.dev",
    knowledge: "Conhecimentos",
    skills: "Habilidades",
    attitudes: "Atitudes",
    knowledgeList: ["Sistemas de Informação", "Golang", "Java", "SQL", "Infraestrutura T.I", "Análise de Dados"],
    skillsList: ["Facilidade para aprender", "Ótimo raciocínio lógico", "Manutenção de infraestrutura T.I", "Inglês Avançado"],
    tools: "Ferramentas",
    toolsList: ["Git", "Docker", "Linux", "Postman", "Active Directory"],
    experience: "Experiência",
    experienceList: [
      { title: "Auxiliar de T.I.", company: "New Line Tecnologia Em Segurança Ltda", link: "https://newlineseguranca.com.br/", period: "Novembro 2025 - Atualmente", description: "Atuação direta em suporte, manutenção de infraestrutura, Active Directory e monitoramento contínuo da rede." },
      { title: "Estagiário de T.I.", company: "New Line Tecnologia Em Segurança Ltda", link: "https://newlineseguranca.com.br/", period: "Agosto 2023 - Outubro 2025", description: "Experiência com redes, montagem e manutenção de computadores, e assistência na infraestrutura de T.I." },
      { title: "Monitor de Alarmes e Câmeras de Segurança", company: "Safety House - Serviços de Segurança LTDA", link: "https://safetyhouse.com.br/", period: "Outubro 2021 - Março 2022", description: "Monitoramento de alarmes e câmeras de segurança durante o período noturno." }
    ],
    education: "Formação",
    educationList: [
      { course: "Sistemas de Informação (Bacharelado)", institution: "Instituto Federal de Goiás, Goiânia", link: "https://www.ifg.edu.br/", period: "Agosto 2025 - Atualmente", description: "Foco em desenvolvimento de software, gestão da informação e infraestrutura tecnológica." },
      { course: "Ciências da Computação", institution: "Instituto Federal de Goiás, Anápolis", link: "https://www.ifg.edu.br/", period: "Fevereiro 2020 - Julho 2025", description: "Estudos em Pesquisa Operacional, Algoritmos, Estrutura de Dados e Aprendizado de Máquina." }
    ],
    manager: "Gerente",
    calculatorTitle: "OCEANIA CALC",
    itemCategory: "Categoria do Item",
    selectCategory: "Selecione uma Categoria",
    farm: "Farm",
    weapons: "Armas",
    ammunition: "Munições",
    drugs: "Drogas",
    contraband: "Contrabando",
    illegalServices: "Serviços Ilegais",
    item: "Item",
    quantity: "Quantidade",
    totalWithPartnership: "Total com Parceria",
    totalWithoutPartnership: "Total sem Parceria",
    unitPriceWithPartnership: "Preço Un. (Com Parceria)",
    unitPriceWithoutPartnership: "Preço Un. (Sem Parceria)",
    plans: "Planos",
    discordBotPlans: "Planos de Bot para Discord",
    fivemFactionPlans: "Planos de Facção para FiveM",
    monthly: "Mensal",
    annually: "Anual",
    subscribe: "Assinar",
    month: "mês",
    year: "ano",
    quarterly: "Trimestral",
    lifetime: "Vitalício",
    annualDiscount: "Economize 16% com o plano anual!",
    fmmModManagerPlans: "Planos do Gerenciador de Mods FiveM",
    fmmQuarterlySavings: "Economize ~11% vs mensal",
    fmmLifetimeNote: "Pagamento único - acesso para sempre",
    fmmForever: "para sempre",
    fmmRecommended: "Recomendado",
    fmmOneTimePayment: "pagamento único",
    fmmLicenseDelivery: "Após o pagamento, sua licença será entregue automaticamente.",
    fmmDownloadFree: "Grátis",
    dbOfflineTitle: "Serviço temporariamente indisponível",
    dbOfflineMessage: "Nosso banco de dados está offline no momento. Já enviamos um alerta e ele será restaurado em breve. Tente novamente mais tarde.",
    discordPlans: [
        { title: "Básico", price: 35, features: ["logs", "verification", "security", "moderation", "limited_customization", "paid_features"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=01bac1298ea84b9ea952483a553811ec", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=52e56a46d88345418fe1472f0c443e1d" } },
        { title: "Intermediário", price: 50, features: ["all_basic", "vip", "five_new_features", "advanced_security", "hour_counting"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=59aab9185a0e4ca4be5334bfabd8dd6d", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=352c67ff541b492fb3126d3164928057" } },
        { title: "Avançado", price: 70, features: ["all_intermediate", "unlimited_features", "full_customization", "large_servers", "priority_support", "proactive_monitoring"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=47804a73dbed428bb9cec0852384e45c", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=60abafc09b384dee87ea6a0504bdd8cc" } }
    ],
    fivemPlans: [
        { title: "Base", price: 35, features: ["basic_features", "sell_logs", "production_logs", "sets"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=01bac1298ea84b9ea952483a553811ec", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=52e56a46d88345418fe1472f0c443e1d" } },
        { title: "Intermediário", price: 50, features: ["all_base", "financial_panel", "report_system"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=59aab9185a0e4ca4be5334bfabd8dd6d", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=352c67ff541b492fb3126d3164928057" } },
        { title: "Avançado", price: 70, features: ["all_intermediate_fivem", "full_customization_fivem", "free_new_features", "priority_support_fivem"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=47804a73dbed428bb9cec0852384e45c", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=60abafc09b384dee87ea6a0504bdd8cc" } }
    ],
    planFeatures: {
        discord: { logs: "Módulos de log", verification: "Verificação de entrada", security: "Módulos de segurança", moderation: "Moderação", limited_customization: "Customização limitada", paid_features: "Novas funcionalidades pagas à parte", all_basic: "Tudo do plano Básico", vip: "Sistemas de VIP", five_new_features: "Até 5 funcionalidades novas inclusas", advanced_security: "Sistemas de segurança mais avançados", hour_counting: "Sistema de contagem de horas", all_intermediate: "Tudo do plano Intermediário", unlimited_features: "Funcionalidades novas ilimitadas", full_customization: "Bot totalmente customizável", large_servers: "Preparado para GRANDES servidores", priority_support: "Suporte prioritário", proactive_monitoring: "Monitoramento proativo do desempenho" },
        fivem: { basic_features: "Funcionalidades do plano Base", sell_logs: "Logs de venda", production_logs: "Logs de produção", sets: "Sets", all_base: "Tudo do plano Base", financial_panel: "Painel financeiro", report_system: "Sistema de relatórios", all_intermediate_fivem: "Tudo do plano Intermediário", full_customization_fivem: "100% de personalização", free_new_features: "Novas funcionalidades gratuitas", priority_support_fivem: "Suporte prioritário" }
    },
    fmmPlans: [
        { title: "Básico", prices: { monthly: 15, quarterly: 40, lifetime: 80 }, features: ["fmm_sound_packs", "fmm_citizen_extras", "fmm_servers_list", "fmm_one_click_server", "fmm_favorite_servers", "fmm_fivem_settings", "fmm_settings_presets", "fmm_apply_registry", "fmm_hardware_analysis"], paymentLinks: { monthly: "#", quarterly: "#", lifetime: "#" } },
        { title: "Pro", prices: { monthly: 35, quarterly: 100, lifetime: 200 }, features: ["fmm_all_basic", "fmm_restore_services", "fmm_save_profile", "fmm_load_profile", "fmm_rename_profile", "fmm_auto_reconnect"], paymentLinks: { monthly: "#", quarterly: "#", lifetime: "#" } }
    ],
    fmmPlanFeatures: {
        fmm_scan_mods: "Escanear e visualizar mods instalados",
        fmm_rpf_mods: "Ativar/desativar mods RPF",
        fmm_view_optimizations: "Ver otimizações disponíveis",
        fmm_sound_packs: "Ativar/desativar sound packs",
        fmm_citizen_extras: "Ativar/desativar citizen extras",
        fmm_servers_list: "Salvar e gerenciar lista de servidores",
        fmm_one_click_server: "Entrar em servidor com um clique",
        fmm_favorite_servers: "Favoritar servidores",
        fmm_fivem_settings: "Editar configurações gráficas e de rede",
        fmm_settings_presets: "Salvar e carregar presets de configuração",
        fmm_apply_registry: "Aplicar otimizações de registro do Windows",
        fmm_hardware_analysis: "Análise de hardware e saúde do sistema",
        fmm_all_basic: "Tudo do plano Básico",
        fmm_restore_services: "Reativar serviços bloqueados pelo Windows",
        fmm_save_profile: "Salvar combinação de mods como perfil",
        fmm_load_profile: "Carregar perfil salvo com um clique",
        fmm_rename_profile: "Renomear perfis",
        fmm_auto_reconnect: "Auto-reconexão após crash no servidor",
    },
    urlShortenerTitle: "Encurtador de URL",
    urlShortenerPlaceholder: "Digite a URL para encurtar",
    urlShortenerButton: "Encurtar",
    urlShortenerLoading: "Encurtando...",
    urlShortenerResult: "URL Encurtada:",
    urlShortenerError: "Ocorreu um erro. Por favor, tente novamente.",
    urlShortenerEnterUrl: "Por favor, digite uma URL.",
    financeManagerTitle: "Gerenciador Financeiro",
    addTransaction: "Adicionar Transação",
    transactionDescription: "Descrição",
    amount: "Valor",
    category: "Categoria",
    type: "Tipo",
    income: "Receita",
    expense: "Despesa",
    bank: "Banco",
    date: "Data",
    add: "Adicionar",
    totalBalance: "Saldo Total",
    banks: "Bancos",
    addBank: "Adicionar Banco",
    bankName: "Nome do Banco",
    initialBalance: "Saldo Inicial",
    recentTransactions: "Transações Recentes",
    edit: "Editar",
    delete: "Excluir",
    update: "Atualizar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    confirmDelete: "Tem certeza que deseja excluir esta transação?",
    confirmDeleteBank: "Tem certeza que deseja excluir este banco? Todas as transações associadas serão perdidas.",
    expenseByCategory: "Despesas por Categoria",
    expenseByType: "Despesas por Tipo",
    pix: "Pix",
    card: "Cartão",
    futureExpenses: "Despesas Futuras",
    paymentMonth: "Mês de Pagamento",
    pay: "Pagar",
    selectBankToPay: "Selecione o banco para pagar",
    makeTransfer: "Realizar Transferência",
    from: "De",
    to: "Para",
    transfer: "Transferir",
    transferring: "Transferindo...",
    transferSuccess: "Transferência realizada com sucesso.",
    transferError: "Falha ao realizar transferência.",
    allFieldsRequired: "Todos os campos são obrigatórios.",
    transferDescriptionPlaceholder: "Ex: Transferência entre contas",
    todoListTitle: "Lista de Tarefas",
    addTodo: "Adicionar Tarefa",
    updateTask: "Atualizar Tarefa",
    addOrEditTask: "Adicionar ou editar uma tarefa...",
    enterTodo: "Digite uma nova tarefa",
    allDay: "Dia todo",
    specificTime: "Horário Específico",
    close: "Fechar",
    todos: "Tarefas",
    completed: "Concluídas",
    pending: "Pendentes",
    editTask: "Editar Tarefa",
    save: "Salvar",
    overdue: "Atrasadas",
    today: "Hoje",
    thisWeek: "Essa Semana",
    upcoming: "Próximas",
    noTasks: "Nenhuma tarefa ainda. Adicione uma para começar!",
    viewCalendar: "Ver Calendário",
    priority: "Prioridade",
    priorityLow: "Baixa",
    priorityMedium: "Média",
    priorityHigh: "Alta",
    recurrence: "Recorrência",
    recurrenceNone: "Nenhuma",
    recurrenceDaily: "Diária",
    recurrenceWeekly: "Semanal",
    recurrenceMonthly: "Mensal",
    fullName: "Davi Monteiro Fonseca",
    rouletteParticipants: "Participantes",
    rouletteDraw: "Sortear",
    rouletteNamesUnit: "nome(s)",
    rouletteSpinButton: "Girar a Roleta",
    rouletteSpinning: "Sorteando...",
    rouletteWinners: "Vencedor(es):",
    rouletteNamesPlaceholder: "Digite os nomes, um por linha...",
    calculatorProduct: "Produto",
    calculatorAddProduct: "Adicionar Produto",
    calculatorAddedItems: "Itens Adicionados",
    calculatorNoItems: "Nenhum item adicionado ainda.",
    calculatorRemove: "Remover",
    calculatorClearAll: "Limpar Tudo",
    calculatorSummary: "Resumo do Cálculo",
    calculatorGunpowder: "Total de Pólvora Usada",
    calculatorMoneyUsed: "Total de Dinheiro Usado",
    calculatorTotalCharge: "Total a Cobrar do Cliente",
    calculatorCommission: "Comissão (20%)",
    calculatorTotalFaction: "Total para Facção",
    calculatorWithoutPartnership: "Sem Parceria",
    calculatorWithPartnership: "Com Parceria",
    privacyPolicy: "Política de Privacidade",
    termsOfService: "Termos de Serviço",
    // Copy do painel "versão não encontrada" (rotas /legal/:version/...). Não é
    // conteúdo versionado - é UI do site, por isso vive aqui e não em
    // src/content/legal, que só guarda snapshots imutáveis de cada versão.
    legalVersionNotFoundTitle: "Versão não encontrada",
    legalVersionNotFoundPrefix: "A versão",
    legalVersionNotFoundSuffix: "deste documento não existe em nosso histórico.",
    legalVersionNotFoundExplanation: "Para não afirmar um contrato que você nunca aceitou, não mostramos o texto vigente no lugar dela.",
    legalVersionNotFoundLink: "Ver a versão atual deste documento",
    privacy: {
      title: "Política de Privacidade",
      introduction: "Introdução",
      introductionText: "Bem-vindo à nossa Política de Privacidade. Sua privacidade é importante para nós. Esta política explica como coletamos, usamos e protegemos suas informações quando você utiliza nosso site.",
      dataCollection: "Coleta de Dados",
      dataCollectionText: "Nós coletamos apenas as informações estritamente necessárias para o funcionamento dos recursos que você decide utilizar em nosso sistema, como e-mail e dados de sessão de usuário criptografados. Não vendemos ou usamos seus dados para rastreamento de anúncios de terceiros.",
      dataCollectionToken: "",
      dataCollectionTokenText: "",
      dataCollectionDisclaimer: "",
      dataUsage: "Uso dos Dados",
      dataUsageText: "Utilizamos suas informações de conta exclusivamente para os seguintes propósitos:",
      dataUsageImport: "Personalização: Fornecer painéis de acesso pessoal como a lista de tarefas e gestão financeira.",
      dataUsageCreate: "Autenticação: Garantir que você faça login em sua conta com segurança para manter seus dados privados longe de terceiros.",
      dataUsageDelete: "",
      dataUsagePolicy: "",
      dataSharing: "Compartilhamento de Dados",
      dataSharingText: "Nós não compartilhamos, vendemos ou alugamos suas informações pessoais com terceiros sob nenhuma circunstância.",
      security: "Segurança",
      securityText: "Tomamos medidas de segurança rigorosas para proteger suas informações. Todos os acessos são feitos através de tokens de autenticação temporários (JWT), que são transmitidos por um canal seguro e validados pelo nosso servidor. Senhas são armazenadas com algoritmos de Hash irreversíveis.",
      revokingAccess: "Exclusão de Conta",
      revokingAccessText: "Você pode solicitar a exclusão total da sua conta e dados do sistema entrando em contato conosco através da página de contato.",
      contact: "Contato",
      contactText: "Se você tiver alguma dúvida sobre esta Política de Privacidade ou precisar solicitar a exclusão da sua conta, entre em contato conosco através do formulário de contato do site."
    },
    terms: {
        title: "Termos de Serviço",
        acceptance: "Aceitação dos Termos",
        acceptanceText: "Ao acessar e utilizar nosso site e seus serviços, você aceita e concorda em estar vinculado aos termos e disposições deste acordo. Se você não concorda com algum destes termos, você não está autorizado a usar este site.",
        serviceDescription: "Descrição do Serviço",
        serviceDescriptionText: "Nosso site oferece um conjunto de ferramentas pessoais, incluindo lista de tarefas e gerenciador financeiro. Este serviço é fornecido 'como está', sem garantias de qualquer tipo.",
        userConduct: "Conduta do Usuário",
        userConductText: "Você concorda em não usar o serviço para qualquer finalidade ilegal ou proibida por estes termos. Você é responsável por toda a sua atividade em conexão com o serviço.",
        googleIntegration: "Privacidade de Dados",
        googleIntegrationText: "Ao utilizar nossos serviços, você nos confia alguns dados pessoais. Nos comprometemos a manter o sigilo de suas informações, conforme descrito na nossa Política de Privacidade.",
        liabilityLimitation: "Limitação de Responsabilidade",
        liabilityLimitationText: "Em nenhuma circunstância o proprietário deste site será responsável por quaisquer danos diretos, indiretos, incidentais, especiais ou consequenciais que resultem do uso ou da incapacidade de usar este serviço. O uso do serviço é por sua conta e risco. Não oferecemos garantia de que o serviço estará livre de erros, interrupções ou perda de dados.",
        termsModification: "Modificações nos Termos",
        termsModificationText: "Reservamo-nos o direito de modificar estes termos a qualquer momento. Aconselhamos que você revise esta página periodicamente para estar ciente de quaisquer alterações. O uso continuado do site após a publicação de alterações constituirá sua aceitação dos novos termos.",
        contact: "Contato",
        contactText: "Se você tiver dúvidas sobre estes termos, entre em contato através da nossa página de contato."
    },
    home: {
      systemLabel: 'DAVIMF / SYS',
      systemId: 'DVM-001',
      headline: 'Ideias viram sistemas.\nSistemas geram resultados.',
      sub: 'Software, automações e produtos digitais - da arquitetura à produção.',
      ctaProducts: 'Ver produtos',
      ctaWork: 'Conhecer meu trabalho',
      evidence: {
        payments: { label: 'PAYMENTS', value: 'Mercado Pago · webhooks assinados · reembolso self-service' },
        licensing: { label: 'LICENSING', value: 'chave por máquina · revogação · vitalícia' },
        infra: { label: 'INFRA', value: 'VPS própria · Docker · Nginx · PostgreSQL' },
      },
      work: {
        heading: 'SELECTED WORK',
        fmm: {
          kicker: '01 / PRODUCT',
          title: 'FiveM Mod Manager',
          description: 'Ative e desative mods com um clique. Perfis salvam mods, citizens e configuração de uma vez.',
          tags: 'WINDOWS · MODS · PERFIS · OTIMIZAÇÃO · LICENSING',
          link: 'Ver FMM',
          shots: {
            primary: {
              label: 'MODS',
              alt: 'Grade de mods do FiveM Mod Manager, com as seções Estradas e Gráficos e mods ativos e inativos.',
            },
            secondary: {
              label: 'OTIMIZAÇÃO',
              alt: 'Painel de otimização do FiveM Mod Manager mostrando CPU, GPU e serviços do Windows relevantes para o FiveM.',
            },
          },
        },
        basebot: {
          kicker: '02 / PLATFORM',
          title: 'BaseBot',
          description: 'Bots modulares e painel de configuração para Discord.',
          tags: 'DISCORD · AUTOMAÇÃO · MODERAÇÃO · DASHBOARD',
          link: 'Ver BaseBot',
          shots: {
            primary: {
              label: 'SERVIDORES',
              alt: 'Painel de servidores do BaseBot mostrando os servidores Discord do proprietário.',
            },
            secondary: {
              label: 'CONFIGURAÇÃO',
              alt: 'Painel de configuração de um bot no BaseBot exibindo opções de personalização.',
            },
          },
        },
      },
      tools: {
        heading: 'TOOLS',
        seeAll: 'Ver todas',
        notes: { name: 'Notes', description: 'Anotações rápidas e sincronizadas' },
        url: { name: 'URL', description: 'Encurtador de URLs' },
        finance: { name: 'Finance', description: 'Controle pessoal de gastos' },
        password: { name: 'Password', description: 'Gerador seguro' },
        todo: { name: 'Tarefas', description: 'Lista de tarefas simples' },
        roulette: { name: 'Roleta', description: 'Sorteio aleatório' },
      },
      toolsPage: {
        title: 'Ferramentas',
        intro: 'Utilitários que construí para resolver problemas meus e deixei abertos para quem precisar.',
      },
      about: {
        heading: 'ABOUT',
        teaser: 'Eu construo backend, bots, ferramentas e automações. Comecei resolvendo problemas meus e continuei transformando essas soluções em produtos.',
        link: 'Sobre mim',
        intro: 'Eu construo backend, bots, ferramentas e automações - e também soluções sob medida: watchdogs, aplicações personalizadas e integrações. O que eu faço é pegar uma ideia solta e trazer para a realidade de forma estruturada.',
        buildHeading: 'O QUE EU CONSTRUO',
      },
      projects: {
        kinds: { product: 'PRODUTOS', site: 'SITES', tools: 'FERRAMENTAS' },
        custom: { label: 'SOB MEDIDA', value: 'Watchdogs, aplicações personalizadas, integrações e automações.' },
        fmm: { name: 'FiveM Mod Manager', description: 'Gerenciador de mods, perfis e otimização para FiveM.' },
        basebot: { name: 'BaseBot', description: 'Bots modulares e painel de configuração para Discord.' },
        davimfdev: { name: 'davimf.dev', description: 'Este site: produtos, pagamentos, licenciamento e ferramentas.' },
        boasvindas: { name: 'boasvindas.online', description: 'Landing pages para hospedagem, com editor e QR para hóspedes.' },
        tools: { name: 'Ferramentas', description: 'Seis utilitários abertos, do encurtador ao gerador de senhas.' },
      },
      portfolio: {
        title: 'Projetos',
        intro: 'Tudo que eu construí e mantenho, com as tecnologias de cada um.',
        filterLabel: 'FILTRAR POR TECNOLOGIA',
        clear: 'Limpar',
        count: 'projetos',
        countOne: 'projeto',
      },
      stack: {
        heading: 'STACK',
        runtime: 'RUNTIME',
        data: 'DATA',
        infra: 'INFRA',
        platforms: 'PLATFORMS',
      },
      contact: {
        question: 'Tem um problema interessante?',
        invite: 'Vamos construir alguma coisa.',
        cta: 'Entrar em contato',
      },
      footer: {
        builtIn: 'Feito no Brasil',
        runningOn: 'Rodando em Linux',
      },
      nav: {
        projects: 'Projetos',
        products: 'Produtos',
        tools: 'Ferramentas',
        about: 'Sobre',
        account: 'Conta',
        menu: 'Menu',
      },
    },
  },
  en: {
    greeting: "Hello, I'm",
    description: "A backend developer with experience in creating robust services and Discord bots. Currently working as an I.T Assistant, focused on creating clean and modern solutions.",
    availableForWork: "Available for new projects",
    cleanCode: "Clean Code",
    cleanCodeDesc: "Writing maintainable, scalable, and efficient solutions.",
    modernUI: "Modern UI/UX",
    modernUIDesc: "Crafting beautiful and intuitive user experiences.",
    responsive: "Responsive",
    responsiveDesc: "Perfect execution across all devices and screen sizes.",
    viewWork: "View My Work",
    getInTouch: "Get in Touch",
    portfolio: "Portfolio",
    resume: "Resume",
    products: "Products",
    contact: "Contact",
    features: "Features",
    todoList: "To-Do List",
    financeManager: "Finances",
    calculator: "Calculator",
    urlShortener: "URL Shortener",
    roulette: "Roulette",
    passwordGenerator: "Password Generator",
    pwgenTitle: "Password Generator",
    pwgenSubtitle: "Generate strong passwords and passphrases. Nothing is sent to servers.",
    pwgenTabPassword: "Password",
    pwgenTabPassphrase: "Passphrase",
    pwgenModeRandom: "Random",
    pwgenModeWords: "With words",
    pwgenLength: "Length",
    pwgenLengthHint: "Value between 5 and 128.",
    pwgenUppercase: "Uppercase (A-Z)",
    pwgenLowercase: "Lowercase (a-z)",
    pwgenNumbers: "Numbers (0-9)",
    pwgenSymbols: "Symbols (!@#$%&*)",
    pwgenMinNumbers: "Min numbers",
    pwgenMinSymbols: "Min symbols",
    pwgenDigitRun: "Digit run",
    pwgenSymbolStyle: "Symbol style",
    pwgenSymbolNone: "None",
    pwgenSymbolSeparator: "Separator between words",
    pwgenSymbolWrapped: "Separator + wrapper",
    pwgenMixedCase: "Random capitalization",
    pwgenWordCount: "Number of words",
    pwgenSeparator: "Separator",
    pwgenSepDash: "Dash ( - )",
    pwgenSepDot: "Dot ( . )",
    pwgenSepUnderscore: "Underscore ( _ )",
    pwgenSepSpace: "Space",
    pwgenSepNone: "None",
    pwgenCapitalize: "Capitalize words",
    pwgenIncludeNumber: "Include number",
    pwgenOptions: "Options",
    pwgenHistory: "History",
    pwgenHistoryEmpty: "No passwords generated yet.",
    pwgenClearHistory: "Clear history",
    pwgenCopy: "Copy",
    pwgenCopied: "Copied!",
    pwgenRegenerate: "Regenerate",
    pwgenShow: "Show",
    pwgenHide: "Hide",
    pwgenNoCharset: "Select at least one character type.",
    pwgenMinError: "The sum of minimums cannot exceed the length.",
    login: "Login",
    register: "Register",
    logout: "Logout",
    rights: "All rights reserved.",
    contactP: "Contact Me",
    connect: "Connect With Me",
    name: "Name",
    message: "Message",
    productsAndServices: "Product & Services",
    learnMore: "Learn More",
    buyNow: "Buy Now",
    sendMessage: "Send Message",
    viewProject: "View project",
    productList: [
        { id: 1, name: "Discover the discord bots", description: "A fully customizable bot focused on moderation and security.", image: "https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/4088758/cover_image/retina_1708x683/cover-how-to-make-a-discord-bot-0afaa27d630de8c4b711f5cd5abbf01f.png", link: "/plans" },
        { id: 2, name: "FiveM Mod Manager", description: "Manage your FiveM mods with just one click. Safely install, enable, and disable sound, RPF, and Citizens mods with automatic backups and performance optimizations.", image: "https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/270123807/original/2e13089eeeef09bbb2a04d238dce1f419b5a7268/install-gta-fivem-server-with-qbcore-linux-or-windows.png", link: "/fmm" }
    ],
    downloadPDF: "Download PDF",
    personalInfo: "Personal Information",
    phone: "(62) 98608-9609",
    email: "davi@davimf.dev",
    knowledge: "Knowledge",
    skills: "Skills",
    attitudes: "Attitudes",
    knowledgeList: ["Information Systems", "Golang", "Java", "SQL", "I.T Infrastructure", "Data Analysis"],
    skillsList: ["Fast learner", "Great logical reasoning", "I.T Infrastructure maintenance", "Advanced English"],
    tools: "Tools",
    toolsList: ["Git", "Docker", "Linux", "Postman", "Active Directory"],
    experience: "Experience",
    experienceList: [
        { title: "I.T Assistant", company: "New Line Tecnologia Em Segurança Ltda", link: "https://newlineseguranca.com.br/", period: "November 2025 - Present", description: "Direct involvement in tech support, infrastructure maintenance, Active Directory, and continuous network monitoring." },
        { title: "I.T Intern", company: "New Line Tecnologia Em Segurança Ltda", link: "https://newlineseguranca.com.br/", period: "August 2023 - October 2025", description: "Experience with networks, computer assembly and maintenance, and I.T infrastructure assistance." },
        { title: "Security Alarm and Camera Monitor", company: "Safety House - Security Services LTDA", link: "https://safetyhouse.com.br/", period: "October 2021 - March 2022", description: "Monitored security alarms and cameras during night shifts." }
    ],
    education: "Education",
    educationList: [
        { course: "Information Systems (Bachelor's)", institution: "Federal Institute of Goiás, Goiânia", link: "https://www.ifg.edu.br/", period: "August 2025 - Present", description: "Focused on software development, information management, and technological infrastructure." },
        { course: "Computer Science", institution: "Federal Institute of Goiás, Anápolis", link: "https://www.ifg.edu.br/", period: "February 2020 - July 2025", description: "Studied Operational Research, Algorithms, Data Structures, and Machine Learning." }
    ],
    manager: "Manager",
    calculatorTitle: "OCEANIA CALC",
    itemCategory: "Item Category",
    selectCategory: "Select a Category",
    farm: "Farm",
    weapons: "Weapons",
    ammunition: "Ammunition",
    drugs: "Drugs",
    contraband: "Contraband",
    illegalServices: "Illegal Services",
    item: "Item",
    quantity: "Quantity",
    totalWithPartnership: "Total with Partnership",
    totalWithoutPartnership: "Total without Partnership",
    unitPriceWithPartnership: "Unit Price (with Partnership)",
    unitPriceWithoutPartnership: "Unit Price (without Partnership)",
    plans: "Plans",
    discordBotPlans: "Discord Bot Plans",
    fivemFactionPlans: "FiveM Faction Plans",
    monthly: "Monthly",
    annually: "Annually",
    subscribe: "Subscribe",
    month: "month",
    year: "year",
    quarterly: "Quarterly",
    lifetime: "Lifetime",
    annualDiscount: "Save 16% with the annual plan!",
    fmmModManagerPlans: "FiveM Mod Manager Plans",
    fmmQuarterlySavings: "Save ~11% vs monthly",
    fmmLifetimeNote: "One-time payment - lifetime access",
    fmmForever: "forever",
    fmmRecommended: "Recommended",
    fmmOneTimePayment: "one-time payment",
    fmmLicenseDelivery: "After payment, your license will be delivered automatically.",
    fmmDownloadFree: "Free",
    dbOfflineTitle: "Service temporarily unavailable",
    dbOfflineMessage: "Our database is currently offline. We've already sent an alert and it will be restored shortly. Please try again later.",
    discordPlans: [
        { title: "Basic", price: 35, features: ["logs", "verification", "security", "moderation", "limited_customization", "paid_features"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=01bac1298ea84b9ea952483a553811ec", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=52e56a46d88345418fe1472f0c443e1d" } },
        { title: "Intermediate", price: 50, features: ["all_basic", "vip", "five_new_features", "advanced_security", "hour_counting"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=59aab9185a0e4ca4be5334bfabd8dd6d", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=352c67ff541b492fb3126d3164928057" } },
        { title: "Advanced", price: 70, features: ["all_intermediate", "unlimited_features", "full_customization", "large_servers", "priority_support", "proactive_monitoring"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=47804a73dbed428bb9cec0852384e45c", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=60abafc09b384dee87ea6a0504bdd8cc" } }
    ],
    fivemPlans: [
        { title: "Base", price: 35, features: ["basic_features", "sell_logs", "production_logs", "sets"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=01bac1298ea84b9ea952483a553811ec", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=52e56a46d88345418fe1472f0c443e1d" } },
        { title: "Intermediate", price: 50, features: ["all_base", "financial_panel", "report_system"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=59aab9185a0e4ca4be5334bfabd8dd6d", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=352c67ff541b492fb3126d3164928057" } },
        { title: "Advanced", price: 70, features: ["all_intermediate_fivem", "full_customization_fivem", "free_new_features", "priority_support_fivem"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=47804a73dbed428bb9cec0852384e45c", annually: "https://www.mercadopag.com.br/subscriptions/checkout?preapproval_plan_id=60abafc09b384dee87ea6a0504bdd8cc" } }
    ],
    planFeatures: {
        discord: { logs: "Log modules", verification: "Entry verification", security: "Security modules", moderation: "Moderation", limited_customization: "Limited customization", paid_features: "New features paid separately", all_basic: "Everything from the Basic plan", vip: "VIP systems", five_new_features: "Up to 5 new features included", advanced_security: "Advanced security systems", hour_counting: "Hour counting system", all_intermediate: "Everything from the Intermediate plan", unlimited_features: "Unlimited new features", full_customization: "Fully customizable bot", large_servers: "Prepared for LARGE servers", priority_support: "Priority support", proactive_monitoring: "Proactive performance monitoring" },
        fivem: { basic_features: "Base plan features", sell_logs: "Sell logs", production_logs: "Production logs", sets: "Sets", all_base: "Everything from the Base plan", financial_panel: "Financial panel", report_system: "Reporting system", all_intermediate_fivem: "Everything from the Intermediate plan", full_customization_fivem: "100% customization", free_new_features: "Free new features", priority_support_fivem: "Priority support" }
    },
    fmmPlans: [
        { title: "Basic", prices: { monthly: 15, quarterly: 40, lifetime: 80 }, features: ["fmm_sound_packs", "fmm_citizen_extras", "fmm_servers_list", "fmm_one_click_server", "fmm_favorite_servers", "fmm_fivem_settings", "fmm_settings_presets", "fmm_apply_registry", "fmm_hardware_analysis"], paymentLinks: { monthly: "#", quarterly: "#", lifetime: "#" } },
        { title: "Pro", prices: { monthly: 35, quarterly: 100, lifetime: 200 }, features: ["fmm_all_basic", "fmm_restore_services", "fmm_save_profile", "fmm_load_profile", "fmm_rename_profile", "fmm_auto_reconnect"], paymentLinks: { monthly: "#", quarterly: "#", lifetime: "#" } }
    ],
    fmmPlanFeatures: {
        fmm_scan_mods: "Scan and view installed mods",
        fmm_rpf_mods: "Enable/disable RPF mods",
        fmm_view_optimizations: "View available optimizations",
        fmm_sound_packs: "Enable/disable sound packs",
        fmm_citizen_extras: "Enable/disable citizen extras",
        fmm_servers_list: "Save and manage server list",
        fmm_one_click_server: "One-click server join",
        fmm_favorite_servers: "Favorite servers",
        fmm_fivem_settings: "Edit graphics and network settings",
        fmm_settings_presets: "Save and load configuration presets",
        fmm_apply_registry: "Apply Windows registry optimizations",
        fmm_hardware_analysis: "Hardware and system health analysis",
        fmm_all_basic: "Everything from the Basic plan",
        fmm_restore_services: "Re-enable services blocked by Windows",
        fmm_save_profile: "Save current mod combination as profile",
        fmm_load_profile: "Load saved profile with one click",
        fmm_rename_profile: "Rename profiles",
        fmm_auto_reconnect: "Auto-reconnect after server crash",
    },
    urlShortenerTitle: "URL Shortener",
    urlShortenerPlaceholder: "Enter URL to shorten",
    urlShortenerButton: "Shorten",
    urlShortenerLoading: "Shortening...",
    urlShortenerResult: "Shortened URL:",
    urlShortenerError: "An error occurred. Please try again.",
    urlShortenerEnterUrl: "Please enter a URL.",
    financeManagerTitle: "Finance Manager",
    addTransaction: "Add Transaction",
    transactionDescription: "Description",
    amount: "Amount",
    category: "Category",
    type: "Type",
    income: "Income",
    expense: "Expense",
    bank: "Bank",
    date: "Date",
    add: "Add",
    totalBalance: "Total Balance",
    banks: "Banks",
    addBank: "Add Bank",
    bankName: "Bank Name",
    initialBalance: "Initial Balance",
    recentTransactions: "Recent Transactions",
    edit: "Edit",
    delete: "Delete",
    update: "Update",
    cancel: "Cancel",
    confirm: "Confirm",
    confirmDelete: "Are you sure you want to delete this transaction?",
    confirmDeleteBank: "Are you sure you want to delete this bank? All associated transactions will be lost.",
    expenseByCategory: "Expenses by Category",
    expenseByType: "Expenses by Type",
    pix: "Pix",
    card: "Card",
    futureExpenses: "Future Expenses",
    paymentMonth: "Payment Month",
    pay: "Pay",
    selectBankToPay: "Select bank to pay",
    makeTransfer: "Make Transfer",
    from: "From",
    to: "To",
    transfer: "Transfer",
    transferring: "Transferring...",
    transferSuccess: "Transfer completed successfully.",
    transferError: "Failed to complete transfer.",
    allFieldsRequired: "All fields are required.",
    transferDescriptionPlaceholder: "Ex: Transfer between accounts",
    todoListTitle: "To-Do List",
    addTodo: "Add Task",
    updateTask: "Update Task",
    addOrEditTask: "Add or edit a task...",
    enterTodo: "Enter a new todo",
    allDay: "All Day",
    specificTime: "Specific Time",
    close: "Close",
    todos: "Todos",
    completed: "Completed",
    pending: "Pending",
    editTask: "Edit Task",
    save: "Save",
    overdue: "Overdue",
    today: "Today",
    thisWeek: "This Week",
    upcoming: "Upcoming",
    noTasks: "No tasks yet. Add one to get started!",
    viewCalendar: "View Calendar",
    priority: "Priority",
    priorityLow: "Low",
    priorityMedium: "Medium",
    priorityHigh: "High",
    recurrence: "Recurrence",
    recurrenceNone: "None",
    recurrenceDaily: "Daily",
    recurrenceWeekly: "Weekly",
    recurrenceMonthly: "Monthly",
    fullName: "Davi Monteiro Fonseca",
    rouletteParticipants: "Participants",
    rouletteDraw: "Draw",
    rouletteNamesUnit: "name(s)",
    rouletteSpinButton: "Spin the Wheel",
    rouletteSpinning: "Drawing...",
    rouletteWinners: "Winner(s):",
    rouletteNamesPlaceholder: "Enter names, one per line...",
    calculatorProduct: "Product",
    calculatorAddProduct: "Add Product",
    calculatorAddedItems: "Added Items",
    calculatorNoItems: "No items added yet.",
    calculatorRemove: "Remove",
    calculatorClearAll: "Clear All",
    calculatorSummary: "Calculation Summary",
    calculatorGunpowder: "Total Gunpowder Used",
    calculatorMoneyUsed: "Total Money Used",
    calculatorTotalCharge: "Total to Charge Client",
    calculatorCommission: "Commission (20%)",
    calculatorTotalFaction: "Total for Faction",
    calculatorWithoutPartnership: "Without Partnership",
    calculatorWithPartnership: "With Partnership",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    // "Version not found" panel copy (/legal/:version/... routes). Not
    // versioned content - it's site UI, so it lives here rather than in
    // src/content/legal, which only holds immutable per-version snapshots.
    legalVersionNotFoundTitle: "Version not found",
    legalVersionNotFoundPrefix: "Version",
    legalVersionNotFoundSuffix: "of this document does not exist in our history.",
    legalVersionNotFoundExplanation: "To avoid asserting a contract you never agreed to, we do not show the current text in its place.",
    legalVersionNotFoundLink: "View the current version of this document",
    privacy: {
        title: "Privacy Policy",
        introduction: "Introduction",
        introductionText: "Welcome to our Privacy Policy. Your privacy is important to us. This policy explains how we collect, use, and protect your information when you use our website.",
        dataCollection: "Data Collection",
        dataCollectionText: "We only collect the information strictly necessary for the operation of the features you choose to use in our system, such as email and encrypted user session data. We do not sell or use your data for third-party ad tracking.",
        dataCollectionToken: "",
        dataCollectionTokenText: "",
        dataCollectionDisclaimer: "",
        dataUsage: "Data Usage",
        dataUsageText: "We use your account information exclusively for the following purposes:",
        dataUsageImport: "Personalization: To provide access to personal dashboards like your to-do list and financial management.",
        dataUsageCreate: "Authentication: To ensure you can securely log into your account and keep your private data away from third parties.",
        dataUsageDelete: "",
        dataUsagePolicy: "",
        dataSharing: "Data Sharing",
        dataSharingText: "We do not share, sell, or rent your personal information with third parties under any circumstances.",
        security: "Security",
        securityText: "We take rigorous security measures to protect your information. All access is handled via temporary authentication tokens (JWT) transmitted over a secure channel and validated by our server. Passwords are stored using irreversible hashing algorithms.",
        revokingAccess: "Account Deletion",
        revokingAccessText: "You can request the complete deletion of your account and data from our systems by contacting us through the contact page.",
        contact: "Contact",
        contactText: "If you have any questions about this Privacy Policy or need to request the deletion of your account, please contact us through the site's contact form."
    },
    terms: {
        title: "Terms of Service",
        acceptance: "Acceptance of Terms",
        acceptanceText: "By accessing and using our website and its services, you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to any of these terms, you are not authorized to use this site.",
        serviceDescription: "Service Description",
        serviceDescriptionText: "Our site offers a suite of personal tools, including a to-do list and a financial manager. This service is provided 'as is', without warranties of any kind.",
        userConduct: "User Conduct",
        userConductText: "You agree not to use the service for any purpose that is illegal or prohibited by these terms. You are responsible for all of your activity in connection with the service.",
        googleIntegration: "Data Privacy",
        googleIntegrationText: "By using our services, you entrust us with certain personal data. We are committed to maintaining the confidentiality of your information, as described in our Privacy Policy.",
        liabilityLimitation: "Limitation of Liability",
        liabilityLimitationText: "Under no circumstances shall the owner of this site be liable for any direct, indirect, incidental, special, or consequential damages that result from the use of or inability to use this service. Your use of the service is at your sole risk. We do not warrant that the service will be error-free, uninterrupted, or free of data loss.",
        termsModification: "Modifications to Terms",
        termsModificationText: "We reserve the right to modify these terms at any time. We advise you to review this page periodically for any changes. Your continued use of the site after the posting of changes will constitute your acceptance of such changes.",
        contact: "Contact",
        contactText: "If you have any questions about these terms, please contact us through our contact page."
    },
    home: {
      systemLabel: 'DAVIMF / SYS',
      systemId: 'DVM-001',
      headline: 'Ideas become systems.\nSystems deliver results.',
      sub: 'Software, automation, and digital products - from architecture to production.',
      ctaProducts: 'See products',
      ctaWork: 'See my work',
      evidence: {
        payments: { label: 'PAYMENTS', value: 'Mercado Pago · signed webhooks · self-service refunds' },
        licensing: { label: 'LICENSING', value: 'per-machine keys · revocation · lifetime' },
        infra: { label: 'INFRA', value: 'own VPS · Docker · Nginx · PostgreSQL' },
      },
      work: {
        heading: 'SELECTED WORK',
        fmm: {
          kicker: '01 / PRODUCT',
          title: 'FiveM Mod Manager',
          description: 'Toggle mods with one click. Profiles save mods, citizens and configuration all at once.',
          tags: 'WINDOWS · MODS · PROFILES · OPTIMIZATION · LICENSING',
          link: 'See FMM',
          shots: {
            primary: {
              label: 'MODS',
              alt: "FiveM Mod Manager's mods grid, showing the Roads and Graphics sections with active and inactive mods.",
            },
            secondary: {
              label: 'OPTIMIZATION',
              alt: "FiveM Mod Manager's optimization panel showing CPU, GPU and Windows services relevant to FiveM.",
            },
          },
        },
        basebot: {
          kicker: '02 / PLATFORM',
          title: 'BaseBot',
          description: 'Modular bots and a configuration panel for Discord.',
          tags: 'DISCORD · AUTOMATION · MODERATION · DASHBOARD',
          link: 'See BaseBot',
          shots: {
            primary: {
              label: 'SERVERS',
              alt: "BaseBot's servers panel showing the site owner's Discord servers.",
            },
            secondary: {
              label: 'CONFIGURATION',
              alt: "BaseBot's configuration panel for a bot displaying customization options.",
            },
          },
        },
      },
      tools: {
        heading: 'TOOLS',
        seeAll: 'See all',
        notes: { name: 'Notes', description: 'Quick synced notes' },
        url: { name: 'URL', description: 'Link shortener' },
        finance: { name: 'Finance', description: 'Personal expense tracking' },
        password: { name: 'Password', description: 'Secure generator' },
        todo: { name: 'Tasks', description: 'A simple to-do list' },
        roulette: { name: 'Roulette', description: 'Random picker' },
      },
      toolsPage: {
        title: 'Tools',
        intro: 'Utilities I built to solve my own problems and left open for whoever needs them.',
      },
      about: {
        heading: 'ABOUT',
        teaser: 'I build backend, bots, tools and automation. I started by solving my own problems and kept turning those solutions into products.',
        link: 'About me',
        intro: 'I build backend, bots, tools and automation - and bespoke solutions too: watchdogs, custom applications and integrations. What I do is take a loose idea and bring it into reality in a structured way.',
        buildHeading: 'WHAT I BUILD',
      },
      projects: {
        kinds: { product: 'PRODUCTS', site: 'SITES', tools: 'TOOLS' },
        custom: { label: 'BESPOKE', value: 'Watchdogs, custom applications, integrations and automation.' },
        fmm: { name: 'FiveM Mod Manager', description: 'Mod, profile and optimization manager for FiveM.' },
        basebot: { name: 'BaseBot', description: 'Modular bots and a configuration panel for Discord.' },
        davimfdev: { name: 'davimf.dev', description: 'This site: products, payments, licensing and tools.' },
        boasvindas: { name: 'boasvindas.online', description: 'Landing pages for hospitality, with an editor and guest QR codes.' },
        tools: { name: 'Tools', description: 'Six open utilities, from the link shortener to the password generator.' },
      },
      portfolio: {
        title: 'Projects',
        intro: 'Everything I have built and maintain, with the technologies behind each one.',
        filterLabel: 'FILTER BY TECHNOLOGY',
        clear: 'Clear',
        count: 'projects',
        countOne: 'project',
      },
      stack: {
        heading: 'STACK',
        runtime: 'RUNTIME',
        data: 'DATA',
        infra: 'INFRA',
        platforms: 'PLATFORMS',
      },
      contact: {
        question: 'Got an interesting problem?',
        invite: "Let's build something.",
        cta: 'Get in touch',
      },
      footer: {
        builtIn: 'Built in Brazil',
        runningOn: 'Running on Linux',
      },
      nav: {
        projects: 'Projects',
        products: 'Products',
        tools: 'Tools',
        about: 'About',
        account: 'Account',
        menu: 'Menu',
      },
    },
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');
  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, translations: translations[language], legal: legal[language] }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
