import React, { createContext, useContext, useState } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  translations: typeof translations[Language];
}

const translations = {
  pt: {
    greeting: "Olá, me chamo",
    description: "Um desenvolvedor especializado em back-end, com experiência em desenvolvimento de bots para Discord. Atualmente sou estagiário de T.I buscando sempre aprender e crescer na área de tecnologia.",
    viewWork: "Ver Meu Trabalho",
    getInTouch: "Entre em Contato",
    home: "Início",
    portfolio: "Portfólio",
    resume: "Currículo",
    products: "Produtos",
    contact: "Contato",
    features: "Funcionalidades",
    todoList: "Lista de Tarefas",
    financeManager: "Finanças",
    calculator: "Calculadora",
    urlShortener: "Encurtador de URL",
    roulette: "Roleta",
    login: "Login",
    register: "Registrar",
    logout: "Sair",
    rights: "Todos os direitos reservados.",
    contactP: "Contate-me",
    connect: "Fale Comigo",
    name: "Nome",
    message: "Mensagem",
    productsAndServices: "Produtos e Serviços",
    learnMore: "Saiba Mais",
    buyNow: "Comprar",
    sendMessage: "Enviar Mensagem",
    viewProject: "Ver projeto",
    projectsList: [
      { id: 1, title: "Discord Bot", description: "Um bot completamente personalizavel, focado em moderação e segurança.", image: "https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/4088758/cover_image/retina_1708x683/cover-how-to-make-a-discord-bot-0afaa27d630de8c4b711f5cd5abbf01f.png", link: "/plans" }
    ],
    productList: [
      { id: 1, name: "Conhecer os bots do discord", description: "Um bot completamente personálizavel, focado em moderação e segurança.", image: "https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/4088758/cover_image/retina_1708x683/cover-how-to-make-a-discord-bot-0afaa27d630de8c4b711f5cd5abbf01f.png", link: "/plans" }
    ],
    downloadPDF: "Baixar PDF",
    personalInfo: "Dados Pessoais",
    phone: "(62) 98608-9609",
    email: "davimf9702@gmail.com",
    knowledge: "Conhecimentos",
    skills: "Habilidades",
    attitudes: "Atitudes",
    knowledgeList: ["Ciência da Computação", "Golang", "Java", "SQL", "T.I", "Analise de Dados"],
    skillsList: ["Facilidade para aprender", "Ótimo raciocínio lógico", "Capacidade para realizar procedimentos de informática", "Ingles Avançado"],
    tools: "Ferramentas",
    toolsList: ["Git", "Docker", "D-Guard", "Postman"],
    experience: "Experiência",
    experienceList: [
      { title: "Estagiário de T.I.", company: "New Line Tecnologia Em Seguranca Ltda", link: "https://newlineseguranca.com.br/", period: "Agosto 2023 - Atualmente", description: "Experiência com redes, manutenção de infraestrutura, ActiveDirectory e outras tecnologias de monitoramento." },
      { title: "Monitor de Alarmes e Câmeras de Segurança", company: "Safety House - Serviços de Segurança LTDA", link: "https://safetyhouse.com.br/", period: "Outubro de 2021 - Março de 2022", description: "Monitoramento de alarmes e câmeras de segurança durante o período noturno." }
    ],
    education: "Formação",
    educationList: [
      { course: "Ciências da Computação (Superior)", institution: "Instituto Federal de Goiás, Anápolis", link: "https://www.ifg.edu.br/", period: "Fevereiro de 2020 - Atualmente", description: "Curso avaliado pelo e-MEC com 5 pontos (nota máxima). Com ênfase em Desenvolvimento de Software, Pesquisa Operacional e Aprendizado de Máquina." },
      { course: "Ensino Médio", institution: "Colégio Protágoras, Goiânia", link: "http://www.colegioprotagoras.com.br/", period: "Janeiro de 2017 - Dezembro de 2019", description: "Aluno sem reprovações ou dependências. Colégio entre os 3 primeiros colocados de Goiás no ENEM." }
    ],
    manager: "Gerente",
    calculatorTitle: "OCEANIA CALC",
    itemCategory: "Categoria do Item",
    selectCategory: "Selecione uma Categoria",
    farm: "Farm",
    weapons: "Armas",
    ammunition: "Munições",
    drugs: "Drogas",
    contraband: "Contrabando",
    illegalServices: "Serviços Ilegais",
    item: "Item",
    quantity: "Quantidade",
    totalWithPartnership: "Total com Parceria",
    totalWithoutPartnership: "Total sem Parceria",
    unitPriceWithPartnership: "Preço Un. (Com Parceria)",
    unitPriceWithoutPartnership: "Preço Un. (Sem Parceria)",
    plans: "Planos",
    discordBotPlans: "Planos de Bot para Discord",
    fivemFactionPlans: "Planos de Facção para FiveM",
    monthly: "Mensal",
    annually: "Anual",
    subscribe: "Assinar",
    month: "mês",
    year: "ano",
    annualDiscount: "Economize 16% com o plano anual!",
    discordPlans: [
        { title: "Básico", price: 35, features: ["logs", "verification", "security", "moderation", "limited_customization", "paid_features"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=01bac1298ea84b9ea952483a553811ec", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=52e56a46d88345418fe1472f0c443e1d" } },
        { title: "Intermediário", price: 50, features: ["all_basic", "vip", "five_new_features", "advanced_security", "hour_counting"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=59aab9185a0e4ca4be5334bfabd8dd6d", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=352c67ff541b492fb3126d3164928057" } },
        { title: "Avançado", price: 70, features: ["all_intermediate", "unlimited_features", "full_customization", "large_servers", "priority_support", "proactive_monitoring"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=47804a73dbed428bb9cec0852384e45c", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=60abafc09b384dee87ea6a0504bdd8cc" } }
    ],
    fivemPlans: [
        { title: "Base", price: 35, features: ["basic_features", "sell_logs", "production_logs", "sets"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=01bac1298ea84b9ea952483a553811ec", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=52e56a46d88345418fe1472f0c443e1d" } },
        { title: "Intermediário", price: 50, features: ["all_base", "financial_panel", "report_system"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=59aab9185a0e4ca4be5334bfabd8dd6d", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=352c67ff541b492fb3126d3164928057" } },
        { title: "Avançado", price: 70, features: ["all_intermediate_fivem", "full_customization_fivem", "free_new_features", "priority_support_fivem"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=47804a73dbed428bb9cec0852384e45c", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=60abafc09b384dee87ea6a0504bdd8cc" } }
    ],
    planFeatures: {
        discord: { logs: "Módulos de log", verification: "Verificação de entrada", security: "Módulos de segurança", moderation: "Moderação", limited_customization: "Customização limitada", paid_features: "Novas funcionalidades pagas à parte", all_basic: "Tudo do plano Básico", vip: "Sistemas de VIP", five_new_features: "Até 5 funcionalidades novas inclusas", advanced_security: "Sistemas de segurança mais avançados", hour_counting: "Sistema de contagem de horas", all_intermediate: "Tudo do plano Intermediário", unlimited_features: "Funcionalidades novas ilimitadas", full_customization: "Bot totalmente customizável", large_servers: "Preparado para GRANDES servidores", priority_support: "Suporte prioritário", proactive_monitoring: "Monitoramento proativo do desempenho" },
        fivem: { basic_features: "Funcionalidades do plano Base", sell_logs: "Logs de venda", production_logs: "Logs de produção", sets: "Sets", all_base: "Tudo do plano Base", financial_panel: "Painel financeiro", report_system: "Sistema de relatórios", all_intermediate_fivem: "Tudo do plano Intermediário", full_customization_fivem: "100% de personalização", free_new_features: "Novas funcionalidades gratuitas", priority_support_fivem: "Suporte prioritário" }
    },
    urlShortenerTitle: "Encurtador de URL",
    urlShortenerPlaceholder: "Digite a URL para encurtar",
    urlShortenerButton: "Encurtar",
    urlShortenerLoading: "Encurtando...",
    urlShortenerResult: "URL Encurtada:",
    urlShortenerError: "Ocorreu um erro. Por favor, tente novamente.",
    urlShortenerEnterUrl: "Por favor, digite uma URL.",
    financeManagerTitle: "Gerenciador Financeiro",
    addTransaction: "Adicionar Transação",
    amount: "Valor",
    category: "Categoria",
    type: "Tipo",
    income: "Receita",
    expense: "Despesa",
    bank: "Banco",
    date: "Data",
    add: "Adicionar",
    totalBalance: "Saldo Total",
    banks: "Bancos",
    addBank: "Adicionar Banco",
    bankName: "Nome do Banco",
    initialBalance: "Saldo Inicial",
    recentTransactions: "Transações Recentes",
    edit: "Editar",
    delete: "Excluir",
    update: "Atualizar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    confirmDelete: "Tem certeza que deseja excluir esta transação?",
    confirmDeleteBank: "Tem certeza que deseja excluir este banco? Todas as transações associadas serão perdidas.",
    expenseByCategory: "Despesas por Categoria",
    expenseByType: "Despesas por Tipo",
    pix: "Pix",
    card: "Cartão",
    futureExpenses: "Despesas Futuras",
    paymentMonth: "Mês de Pagamento",
    pay: "Pagar",
    selectBankToPay: "Selecione o banco para pagar",
    makeTransfer: "Realizar Transferência",
    from: "De",
    to: "Para",
    transfer: "Transferir",
    transferring: "Transferindo...",
    transferSuccess: "Transferência realizada com sucesso.",
    transferError: "Falha ao realizar transferência.",
    allFieldsRequired: "Todos os campos são obrigatórios.",
    transferDescriptionPlaceholder: "Ex: Transferência entre contas",
    todoListTitle: "Lista de Tarefas",
    addTodo: "Adicionar Tarefa",
    updateTask: "Atualizar Tarefa",
    addOrEditTask: "Adicionar ou editar uma tarefa...",
    enterTodo: "Digite uma nova tarefa",
    allDay: "Dia todo",
    specificTime: "Horário Específico",
    close: "Fechar",
    todos: "Tarefas",
    completed: "Concluídas",
    pending: "Pendentes",
    editTask: "Editar Tarefa",
    save: "Salvar",
    overdue: "Atrasadas",
    today: "Hoje",
    thisWeek: "Essa Semana",
    upcoming: "Próximas",
    noTasks: "Nenhuma tarefa ainda. Adicione uma para começar!",
    viewCalendar: "Ver Calendário",
    priority: "Prioridade",
    priorityLow: "Baixa",
    priorityMedium: "Média",
    priorityHigh: "Alta",
    recurrence: "Recorrência",
    recurrenceNone: "Nenhuma",
    recurrenceDaily: "Diária",
    recurrenceWeekly: "Semanal",
    recurrenceMonthly: "Mensal",
    connectGoogleCalendar: "Conectar com Google Calendar",
    privacyPolicy: "Política de Privacidade",
    termsOfService: "Termos de Serviço",
    privacy: {
      title: "Política de Privacidade",
      introduction: "Introdução",
      introductionText: "Bem-vindo à nossa Política de Privacidade. Sua privacidade é importante para nós. Esta política explica como coletamos, usamos e protegemos suas informações quando você utiliza nosso site e, especificamente, a funcionalidade de integração com o Google Calendar.",
      dataCollection: "Coleta de Dados",
      dataCollectionText: "Ao conectar sua conta do Google para sincronizar sua agenda, solicitamos sua permissão para acessar seu Google Calendar e Google Tasks. Os únicos dados que armazenamos em nossos servidores são:",
      dataCollectionToken: "Token de Atualização (Refresh Token) do Google:",
      dataCollectionTokenText: "Este é um token seguro que nos permite solicitar novos tokens de acesso para interagir com a API do Google em seu nome, sem que você precise fazer login repetidamente. Este token é armazenado de forma criptografada em nosso banco de dados.",
      dataCollectionDisclaimer: "Nós não armazenamos seus eventos, tarefas, detalhes de agenda, ou sua senha do Google.",
      dataUsage: "Uso dos Dados",
      dataUsageText: "Utilizamos o acesso concedido e o token de atualização exclusivamente para as seguintes finalidades:",
      dataUsageImport: "Importar eventos e tarefas: Ler os itens da sua agenda do Google para exibi-los em sua lista de tarefas no nosso site.",
      dataUsageCreate: "Criar e atualizar eventos: Criar, editar ou marcar eventos como concluídos no seu Google Calendar quando você realiza essas ações no nosso site.",
      dataUsageDelete: "Excluir eventos e tarefas: Remover itens do seu Google Calendar quando você os exclui no nosso site.",
      dataUsagePolicy: "O uso das informações recebidas das APIs do Google seguirá a Política de Dados do Usuário dos Serviços de API do Google, incluindo os requisitos de Uso Limitado.",
      dataSharing: "Compartilhamento de Dados",
      dataSharingText: "Nós não compartilhamos, vendemos ou alugamos suas informações pessoais ou dados do Google com terceiros.",
      security: "Segurança",
      securityText: "Tomamos medidas de segurança para proteger suas informações. O token de atualização do Google é criptografado antes de ser armazenado em nosso banco de dados, adicionando uma camada extra de proteção.",
      revokingAccess: "Revogando o Acesso",
      revokingAccessText: "Você pode revogar o acesso do nosso aplicativo à sua conta do Google a qualquer momento através da página de segurança do Google:",
      contact: "Contato",
      contactText: "Se você tiver alguma dúvida sobre esta Política de Privacidade, entre em contato conosco através do formulário de contato do site."
    },
    terms: {
        title: "Termos de Serviço",
        acceptance: "Aceitação dos Termos",
        acceptanceText: "Ao acessar e utilizar nosso site e seus serviços, você aceita e concorda em estar vinculado aos termos e disposições deste acordo. Se você não concorda com algum destes termos, você não está autorizado a usar este site.",
        serviceDescription: "Descrição do Serviço",
        serviceDescriptionText: "Nosso site oferece um conjunto de ferramentas, incluindo uma lista de tarefas com integração opcional com o Google Calendar e Google Tasks. Este serviço é fornecido 'como está', sem garantias de qualquer tipo.",
        userConduct: "Conduta do Usuário",
        userConductText: "Você concorda em não usar o serviço para qualquer finalidade ilegal ou proibida por estes termos. Você é responsável por toda a sua atividade em conexão com o serviço.",
        googleIntegration: "Integração com o Google",
        googleIntegrationText: "A integração com o Google Calendar e Google Tasks é uma funcionalidade opcional. Ao utilizá-la, você nos concede permissão para acessar e modificar dados em sua agenda e listas de tarefas, conforme descrito em nossa Política de Privacidade. A disponibilidade e o funcionamento desta integração dependem dos serviços e APIs do Google.",
        liabilityLimitation: "Limitação de Responsabilidade",
        liabilityLimitationText: "Em nenhuma circunstância o proprietário deste site será responsável por quaisquer danos diretos, indiretos, incidentais, especiais ou consequenciais que resultem do uso ou da incapacidade de usar este serviço. O uso do serviço é por sua conta e risco. Não oferecemos garantia de que o serviço estará livre de erros, interrupções ou perda de dados.",
        termsModification: "Modificações nos Termos",
        termsModificationText: "Reservamo-nos o direito de modificar estes termos a qualquer momento. Aconselhamos que você revise esta página periodicamente para estar ciente de quaisquer alterações. O uso continuado do site após a publicação de alterações constituirá sua aceitação dos novos termos."
    }
  },
  en: {
    greeting: "Hello, I'm",
    description: "A backend developer with experience in Discord bot development. Currently working as an I.T trainee, always seeking to learn and grow in the technology field.",
    viewWork: "View My Work",
    getInTouch: "Get in Touch",
    home: "Home",
    portfolio: "Portfolio",
    resume: "Resume",
    products: "Products",
    contact: "Contact",
    features: "Features",
    todoList: "To-Do List",
    financeManager: "Finances",
    calculator: "Calculator",
    urlShortener: "URL Shortener",
    roulette: "Roulette",
    login: "Login",
    register: "Register",
    logout: "Logout",
    rights: "All rights reserved.",
    contactP: "Contact Me",
    connect: "Connect With Me",
    name: "Name",
    message: "Message",
    productsAndServices: "Product & Services",
    learnMore: "Learn More",
    buyNow: "Buy Now",
    sendMessage: "Send Message",
    viewProject: "View project",
    projectsList: [
        { id: 1, title: "Discord Bot", description: "A fully customizable bot focused on moderation and security.", image: "https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/4088758/cover_image/retina_1708x683/cover-how-to-make-a-discord-bot-0afaa27d630de8c4b711f5cd5abbf01f.png", link: "/plans" }
    ],
    productList: [
        { id: 1, name: "Discover the discord bots", description: "A fully customizable bot focused on moderation and security.", image: "https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/4088758/cover_image/retina_1708x683/cover-how-to-make-a-discord-bot-0afaa27d630de8c4b711f5cd5abbf01f.png", link: "/plans" }
    ],
    downloadPDF: "Download PDF",
    personalInfo: "Personal Information",
    phone: "(62) 98608-9609",
    email: "davimf9702@gmail.com",
    knowledge: "Knowledge",
    skills: "Skills",
    attitudes: "Attitudes",
    knowledgeList: ["Computer Science", "Golang", "Java", "SQL", "I.T", "Data Analysis"],
    skillsList: ["Fast learner", "Great logical reasoning", "Ability to perform IT procedures", "Advanced English"],
    tools: "Tools",
    toolsList: ["Git", "Docker", "D-Guard", "Postman"],
    experience: "Experience",
    experienceList: [
        { title: "IT Intern", company: "New Line Tecnologia Em Segurança Ltda", link: "https://newlineseguranca.com.br/", period: "August 2023 - Present", description: "Experience with networks, infrastructure maintenance, Active Directory, and other monitoring technologies." },
        { title: "Security Alarm and Camera Monitor", company: "Safety House - Security Services LTDA", link: "https://safetyhouse.com.br/", period: "October 2021 - March 2022", description: "Monitored security alarms and cameras during night shifts." }
    ],
    education: "Education",
    educationList: [
        { course: "Computer Science (Bachelor's)", institution: "Federal Institute of Goiás, Anápolis", link: "https://www.ifg.edu.br/", period: "February 2020 - Present", description: "Rated 5 stars by e-MEC. Focuses on Software Development, Operational Research, and Machine Learning." },
        { course: "High School", institution: "Colégio Protágoras, Goiânia", link: "http://www.colegioprotagoras.com.br/", period: "January 2017 - December 2019", description: "Graduated without failures. School ranked among the top 3 in Goiás on ENEM." }
    ],
    manager: "Manager",
    calculatorTitle: "OCEANIA CALC",
    itemCategory: "Item Category",
    selectCategory: "Select a Category",
    farm: "Farm",
    weapons: "Weapons",
    ammunition: "Ammunition",
    drugs: "Drugs",
    contraband: "Contraband",
    illegalServices: "Illegal Services",
    item: "Item",
    quantity: "Quantity",
    totalWithPartnership: "Total with Partnership",
    totalWithoutPartnership: "Total without Partnership",
    unitPriceWithPartnership: "Unit Price (with Partnership)",
    unitPriceWithoutPartnership: "Unit Price (without Partnership)",
    plans: "Plans",
    discordBotPlans: "Discord Bot Plans",
    fivemFactionPlans: "FiveM Faction Plans",
    monthly: "Monthly",
    annually: "Annually",
    subscribe: "Subscribe",
    month: "month",
    year: "year",
    annualDiscount: "Save 16% with the annual plan!",
    discordPlans: [
        { title: "Basic", price: 35, features: ["logs", "verification", "security", "moderation", "limited_customization", "paid_features"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=01bac1298ea84b9ea952483a553811ec", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=52e56a46d88345418fe1472f0c443e1d" } },
        { title: "Intermediate", price: 50, features: ["all_basic", "vip", "five_new_features", "advanced_security", "hour_counting"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=59aab9185a0e4ca4be5334bfabd8dd6d", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=352c67ff541b492fb3126d3164928057" } },
        { title: "Advanced", price: 70, features: ["all_intermediate", "unlimited_features", "full_customization", "large_servers", "priority_support", "proactive_monitoring"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=47804a73dbed428bb9cec0852384e45c", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=60abafc09b384dee87ea6a0504bdd8cc" } }
    ],
    fivemPlans: [
        { title: "Base", price: 35, features: ["basic_features", "sell_logs", "production_logs", "sets"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=01bac1298ea84b9ea952483a553811ec", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=52e56a46d88345418fe1472f0c443e1d" } },
        { title: "Intermediate", price: 50, features: ["all_base", "financial_panel", "report_system"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=59aab9185a0e4ca4be5334bfabd8dd6d", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=352c67ff541b492fb3126d3164928057" } },
        { title: "Advanced", price: 70, features: ["all_intermediate_fivem", "full_customization_fivem", "free_new_features", "priority_support_fivem"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=47804a73dbed428bb9cec0852384e45c", annually: "https://www.mercadopag.com.br/subscriptions/checkout?preapproval_plan_id=60abafc09b384dee87ea6a0504bdd8cc" } }
    ],
    planFeatures: {
        discord: { logs: "Log modules", verification: "Entry verification", security: "Security modules", moderation: "Moderation", limited_customization: "Limited customization", paid_features: "New features paid separately", all_basic: "Everything from the Basic plan", vip: "VIP systems", five_new_features: "Up to 5 new features included", advanced_security: "Advanced security systems", hour_counting: "Hour counting system", all_intermediate: "Everything from the Intermediate plan", unlimited_features: "Unlimited new features", full_customization: "Fully customizable bot", large_servers: "Prepared for LARGE servers", priority_support: "Priority support", proactive_monitoring: "Proactive performance monitoring" },
        fivem: { basic_features: "Base plan features", sell_logs: "Sell logs", production_logs: "Production logs", sets: "Sets", all_base: "Everything from the Base plan", financial_panel: "Financial panel", report_system: "Reporting system", all_intermediate_fivem: "Everything from the Intermediate plan", full_customization_fivem: "100% customization", free_new_features: "Free new features", priority_support_fivem: "Priority support" }
    },
    urlShortenerTitle: "URL Shortener",
    urlShortenerPlaceholder: "Enter URL to shorten",
    urlShortenerButton: "Shorten",
    urlShortenerLoading: "Shortening...",
    urlShortenerResult: "Shortened URL:",
    urlShortenerError: "An error occurred. Please try again.",
    urlShortenerEnterUrl: "Please enter a URL.",
    financeManagerTitle: "Finance Manager",
    addTransaction: "Add Transaction",
    amount: "Amount",
    category: "Category",
    type: "Type",
    income: "Income",
    expense: "Expense",
    bank: "Bank",
    date: "Date",
    add: "Add",
    totalBalance: "Total Balance",
    banks: "Banks",
    addBank: "Add Bank",
    bankName: "Bank Name",
    initialBalance: "Initial Balance",
    recentTransactions: "Recent Transactions",
    edit: "Edit",
    delete: "Delete",
    update: "Update",
    cancel: "Cancel",
    confirm: "Confirm",
    confirmDelete: "Are you sure you want to delete this transaction?",
    confirmDeleteBank: "Are you sure you want to delete this bank? All associated transactions will be lost.",
    expenseByCategory: "Expenses by Category",
    expenseByType: "Expenses by Type",
    pix: "Pix",
    card: "Card",
    futureExpenses: "Future Expenses",
    paymentMonth: "Payment Month",
    pay: "Pay",
    selectBankToPay: "Select bank to pay",
    makeTransfer: "Make Transfer",
    from: "From",
    to: "To",
    transfer: "Transfer",
    transferring: "Transferring...",
    transferSuccess: "Transfer completed successfully.",
    transferError: "Failed to complete transfer.",
    allFieldsRequired: "All fields are required.",
    transferDescriptionPlaceholder: "Ex: Transfer between accounts",
    todoListTitle: "To-Do List",
    addTodo: "Add Task",
    updateTask: "Update Task",
    addOrEditTask: "Add or edit a task...",
    enterTodo: "Enter a new todo",
    allDay: "All Day",
    specificTime: "Specific Time",
    close: "Close",
    todos: "Todos",
    completed: "Completed",
    pending: "Pending",
    editTask: "Edit Task",
    save: "Save",
    overdue: "Overdue",
    today: "Today",
    thisWeek: "This Week",
    upcoming: "Upcoming",
    noTasks: "No tasks yet. Add one to get started!",
    viewCalendar: "View Calendar",
    priority: "Priority",
    priorityLow: "Low",
    priorityMedium: "Medium",
    priorityHigh: "High",
    recurrence: "Recurrence",
    recurrenceNone: "None",
    recurrenceDaily: "Daily",
    recurrenceWeekly: "Weekly",
    recurrenceMonthly: "Monthly",
    connectGoogleCalendar: "Connect with Google Calendar",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    privacy: {
        title: "Privacy Policy",
        introduction: "Introduction",
        introductionText: "Welcome to our Privacy Policy. Your privacy is important to us. This policy explains how we collect, use, and protect your information when you use our website and, specifically, the Google Calendar integration feature.",
        dataCollection: "Data Collection",
        dataCollectionText: "When you connect your Google account to sync your calendar, we request your permission to access your Google Calendar and Google Tasks. The only data we store on our servers is:",
        dataCollectionToken: "Google Refresh Token:",
        dataCollectionTokenText: "This is a secure token that allows us to request new access tokens to interact with the Google API on your behalf, without you needing to log in repeatedly. This token is stored encrypted in our database.",
        dataCollectionDisclaimer: "We do not store your events, tasks, calendar details, or your Google password.",
        dataUsage: "Data Usage",
        dataUsageText: "We use the granted access and the refresh token exclusively for the following purposes:",
        dataUsageImport: "Import events and tasks: To read items from your Google Calendar to display them in your to-do list on our site.",
        dataUsageCreate: "Create and update events: To create, edit, or mark events as complete in your Google Calendar when you perform these actions on our site.",
        dataUsageDelete: "Delete events and tasks: To remove items from your Google Calendar when you delete them on our site.",
        dataUsagePolicy: "The use of information received from Google APIs will adhere to the Google API Services User Data Policy, including the Limited Use requirements.",
        dataSharing: "Data Sharing",
        dataSharingText: "We do not share, sell, or rent your personal information or Google data with third parties.",
        security: "Security",
        securityText: "We take security measures to protect your information. The Google refresh token is encrypted before being stored in our database, adding an extra layer of protection.",
        revokingAccess: "Revoking Access",
        revokingAccessText: "You can revoke our application's access to your Google account at any time through Google's security settings page:",
        contact: "Contact",
        contactText: "If you have any questions about this Privacy Policy, please contact us through the site's contact form."
    },
    terms: {
        title: "Terms of Service",
        acceptance: "Acceptance of Terms",
        acceptanceText: "By accessing and using our website and its services, you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to any of these terms, you are not authorized to use this site.",
        serviceDescription: "Service Description",
        serviceDescriptionText: "Our site offers a suite of tools, including a to-do list with optional integration with Google Calendar and Google Tasks. This service is provided 'as is', without warranties of any kind.",
        userConduct: "User Conduct",
        userConductText: "You agree not to use the service for any purpose that is illegal or prohibited by these terms. You are responsible for all of your activity in connection with the service.",
        googleIntegration: "Google Integration",
        googleIntegrationText: "The integration with Google Calendar and Google Tasks is an optional feature. By using it, you grant us permission to access and modify data in your calendar and task lists, as described in our Privacy Policy. The availability and functionality of this integration depend on Google's services and APIs.",
        liabilityLimitation: "Limitation of Liability",
        liabilityLimitationText: "Under no circumstances shall the owner of this site be liable for any direct, indirect, incidental, special, or consequential damages that result from the use of or inability to use this service. Your use of the service is at your sole risk. We do not warrant that the service will be error-free, uninterrupted, or free of data loss.",
        termsModification: "Modifications to Terms",
        termsModificationText: "We reserve the right to modify these terms at any time. We advise you to review this page periodically for any changes. Your continued use of the site after the posting of changes will constitute your acceptance of such changes."
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');
  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
