import React, { createContext, useContext, useState } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  translations: typeof translations[Language];
}

const translations = {
  pt: {
    greeting: "Olá, me chamo",
    description: "Um desenvolvedor com experiência no back-end e criação de serviços e bots robustos. Atualmente sou Auxiliar de T.I, focado em criar soluções limpas e modernas.",
    availableForWork: "Disponível para novos projetos",
    cleanCode: "Código Limpo",
    cleanCodeDesc: "Escrevendo soluções manuteníveis, escaláveis e eficientes.",
    modernUI: "UI/UX Moderno",
    modernUIDesc: "Criando experiências de usuário bonitas e intuitivas.",
    responsive: "Responsivo",
    responsiveDesc: "Execução perfeita em todos os dispositivos e tamanhos de tela.",
    viewWork: "Ver Meu Trabalho",
    getInTouch: "Entre em Contato",
    home: "Início",
    portfolio: "Portfólio",
    resume: "Currículo",
    products: "Produtos",
    contact: "Contato",
    features: "Funcionalidades",
    todoList: "Lista de Tarefas",
    financeManager: "Finanças",
    calculator: "Calculadora",
    urlShortener: "Encurtador de URL",
    roulette: "Roleta",
    login: "Login",
    register: "Registrar",
    logout: "Sair",
    rights: "Todos os direitos reservados.",
    contactP: "Contate-me",
    connect: "Fale Comigo",
    name: "Nome",
    message: "Mensagem",
    productsAndServices: "Produtos e Serviços",
    learnMore: "Saiba Mais",
    buyNow: "Comprar",
    sendMessage: "Enviar Mensagem",
    viewProject: "Ver projeto",
    projectsList: [
      { id: 1, title: "Discord Bot", description: "Um bot completamente personalizavel, focado em moderação e segurança.", image: "https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/4088758/cover_image/retina_1708x683/cover-how-to-make-a-discord-bot-0afaa27d630de8c4b711f5cd5abbf01f.png", link: "/plans" }
    ],
    productList: [
      { id: 1, name: "Conhecer os bots do discord", description: "Um bot completamente personálizavel, focado em moderação e segurança.", image: "https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/4088758/cover_image/retina_1708x683/cover-how-to-make-a-discord-bot-0afaa27d630de8c4b711f5cd5abbf01f.png", link: "/plans" },
      { id: 2, name: "FiveM Mod Manager", description: "Gerencie seus mods do FiveM com apenas um clique. Instale, ative e desative mods de som, RPF e Citizens com backup automático e otimizações de desempenho.", image: "https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/270123807/original/2e13089eeeef09bbb2a04d238dce1f419b5a7268/install-gta-fivem-server-with-qbcore-linux-or-windows.png", link: "/fmm-plans" }
    ],
    downloadPDF: "Baixar PDF",
    personalInfo: "Dados Pessoais",
    phone: "(62) 98608-9609",
    email: "davimf9702@gmail.com",
    knowledge: "Conhecimentos",
    skills: "Habilidades",
    attitudes: "Atitudes",
    knowledgeList: ["Sistemas de Informação", "Golang", "Java", "SQL", "Infraestrutura T.I", "Análise de Dados"],
    skillsList: ["Facilidade para aprender", "Ótimo raciocínio lógico", "Manutenção de infraestrutura T.I", "Inglês Avançado"],
    tools: "Ferramentas",
    toolsList: ["Git", "Docker", "Linux", "Postman", "Active Directory"],
    experience: "Experiência",
    experienceList: [
      { title: "Auxiliar de T.I.", company: "New Line Tecnologia Em Segurança Ltda", link: "https://newlineseguranca.com.br/", period: "Novembro 2025 - Atualmente", description: "Atuação direta em suporte, manutenção de infraestrutura, Active Directory e monitoramento contínuo da rede." },
      { title: "Estagiário de T.I.", company: "New Line Tecnologia Em Segurança Ltda", link: "https://newlineseguranca.com.br/", period: "Agosto 2023 - Outubro 2025", description: "Experiência com redes, montagem e manutenção de computadores, e assistência na infraestrutura de T.I." },
      { title: "Monitor de Alarmes e Câmeras de Segurança", company: "Safety House - Serviços de Segurança LTDA", link: "https://safetyhouse.com.br/", period: "Outubro 2021 - Março 2022", description: "Monitoramento de alarmes e câmeras de segurança durante o período noturno." }
    ],
    education: "Formação",
    educationList: [
      { course: "Sistemas de Informação (Bacharelado)", institution: "Instituto Federal de Goiás, Goiânia", link: "https://www.ifg.edu.br/", period: "Agosto 2025 - Atualmente", description: "Foco em desenvolvimento de software, gestão da informação e infraestrutura tecnológica." },
      { course: "Ciências da Computação", institution: "Instituto Federal de Goiás, Anápolis", link: "https://www.ifg.edu.br/", period: "Fevereiro 2020 - Julho 2025", description: "Estudos em Pesquisa Operacional, Algoritmos, Estrutura de Dados e Aprendizado de Máquina." }
    ],
    manager: "Gerente",
    calculatorTitle: "OCEANIA CALC",
    itemCategory: "Categoria do Item",
    selectCategory: "Selecione uma Categoria",
    farm: "Farm",
    weapons: "Armas",
    ammunition: "Munições",
    drugs: "Drogas",
    contraband: "Contrabando",
    illegalServices: "Serviços Ilegais",
    item: "Item",
    quantity: "Quantidade",
    totalWithPartnership: "Total com Parceria",
    totalWithoutPartnership: "Total sem Parceria",
    unitPriceWithPartnership: "Preço Un. (Com Parceria)",
    unitPriceWithoutPartnership: "Preço Un. (Sem Parceria)",
    plans: "Planos",
    discordBotPlans: "Planos de Bot para Discord",
    fivemFactionPlans: "Planos de Facção para FiveM",
    monthly: "Mensal",
    annually: "Anual",
    subscribe: "Assinar",
    month: "mês",
    year: "ano",
    quarterly: "Trimestral",
    lifetime: "Vitalício",
    annualDiscount: "Economize 16% com o plano anual!",
    fmmModManagerPlans: "Planos do Gerenciador de Mods FiveM",
    discordPlans: [
        { title: "Básico", price: 35, features: ["logs", "verification", "security", "moderation", "limited_customization", "paid_features"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=01bac1298ea84b9ea952483a553811ec", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=52e56a46d88345418fe1472f0c443e1d" } },
        { title: "Intermediário", price: 50, features: ["all_basic", "vip", "five_new_features", "advanced_security", "hour_counting"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=59aab9185a0e4ca4be5334bfabd8dd6d", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=352c67ff541b492fb3126d3164928057" } },
        { title: "Avançado", price: 70, features: ["all_intermediate", "unlimited_features", "full_customization", "large_servers", "priority_support", "proactive_monitoring"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=47804a73dbed428bb9cec0852384e45c", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=60abafc09b384dee87ea6a0504bdd8cc" } }
    ],
    fivemPlans: [
        { title: "Base", price: 35, features: ["basic_features", "sell_logs", "production_logs", "sets"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=01bac1298ea84b9ea952483a553811ec", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=52e56a46d88345418fe1472f0c443e1d" } },
        { title: "Intermediário", price: 50, features: ["all_base", "financial_panel", "report_system"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=59aab9185a0e4ca4be5334bfabd8dd6d", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=352c67ff541b492fb3126d3164928057" } },
        { title: "Avançado", price: 70, features: ["all_intermediate_fivem", "full_customization_fivem", "free_new_features", "priority_support_fivem"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=47804a73dbed428bb9cec0852384e45c", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=60abafc09b384dee87ea6a0504bdd8cc" } }
    ],
    planFeatures: {
        discord: { logs: "Módulos de log", verification: "Verificação de entrada", security: "Módulos de segurança", moderation: "Moderação", limited_customization: "Customização limitada", paid_features: "Novas funcionalidades pagas à parte", all_basic: "Tudo do plano Básico", vip: "Sistemas de VIP", five_new_features: "Até 5 funcionalidades novas inclusas", advanced_security: "Sistemas de segurança mais avançados", hour_counting: "Sistema de contagem de horas", all_intermediate: "Tudo do plano Intermediário", unlimited_features: "Funcionalidades novas ilimitadas", full_customization: "Bot totalmente customizável", large_servers: "Preparado para GRANDES servidores", priority_support: "Suporte prioritário", proactive_monitoring: "Monitoramento proativo do desempenho" },
        fivem: { basic_features: "Funcionalidades do plano Base", sell_logs: "Logs de venda", production_logs: "Logs de produção", sets: "Sets", all_base: "Tudo do plano Base", financial_panel: "Painel financeiro", report_system: "Sistema de relatórios", all_intermediate_fivem: "Tudo do plano Intermediário", full_customization_fivem: "100% de personalização", free_new_features: "Novas funcionalidades gratuitas", priority_support_fivem: "Suporte prioritário" }
    },
    fmmPlans: [
        { title: "Básico", prices: { monthly: 15, quarterly: 40, lifetime: 80 }, features: ["fmm_sound_mods", "fmm_rpf_mods", "fmm_one_click", "fmm_backup", "fmm_basic_support"], paymentLinks: { monthly: "#", quarterly: "#", lifetime: "#" } },
        { title: "Pro", prices: { monthly: 35, quarterly: 100, lifetime: 200 }, features: ["fmm_all_basic", "fmm_citizens", "fmm_citizens_extras", "fmm_performance", "fmm_advanced_logs", "fmm_priority_support"], paymentLinks: { monthly: "#", quarterly: "#", lifetime: "#" } }
    ],
    fmmPlanFeatures: {
        fmm_sound_mods: "Gerenciamento de mods de som",
        fmm_rpf_mods: "Gerenciamento de mods RPF",
        fmm_one_click: "Ativar/desativar mods com 1 clique",
        fmm_backup: "Backup automático antes de instalações",
        fmm_basic_support: "Suporte básico",
        fmm_all_basic: "Tudo do plano Básico",
        fmm_citizens: "Gerenciamento de Citizens",
        fmm_citizens_extras: "Suporte a CitizenExtras",
        fmm_performance: "Otimizações de desempenho do Windows",
        fmm_advanced_logs: "Logs avançados e histórico completo",
        fmm_priority_support: "Suporte prioritário"
    },
    urlShortenerTitle: "Encurtador de URL",
    urlShortenerPlaceholder: "Digite a URL para encurtar",
    urlShortenerButton: "Encurtar",
    urlShortenerLoading: "Encurtando...",
    urlShortenerResult: "URL Encurtada:",
    urlShortenerError: "Ocorreu um erro. Por favor, tente novamente.",
    urlShortenerEnterUrl: "Por favor, digite uma URL.",
    financeManagerTitle: "Gerenciador Financeiro",
    addTransaction: "Adicionar Transação",
    transactionDescription: "Descrição",
    amount: "Valor",
    category: "Categoria",
    type: "Tipo",
    income: "Receita",
    expense: "Despesa",
    bank: "Banco",
    date: "Data",
    add: "Adicionar",
    totalBalance: "Saldo Total",
    banks: "Bancos",
    addBank: "Adicionar Banco",
    bankName: "Nome do Banco",
    initialBalance: "Saldo Inicial",
    recentTransactions: "Transações Recentes",
    edit: "Editar",
    delete: "Excluir",
    update: "Atualizar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    confirmDelete: "Tem certeza que deseja excluir esta transação?",
    confirmDeleteBank: "Tem certeza que deseja excluir este banco? Todas as transações associadas serão perdidas.",
    expenseByCategory: "Despesas por Categoria",
    expenseByType: "Despesas por Tipo",
    pix: "Pix",
    card: "Cartão",
    futureExpenses: "Despesas Futuras",
    paymentMonth: "Mês de Pagamento",
    pay: "Pagar",
    selectBankToPay: "Selecione o banco para pagar",
    makeTransfer: "Realizar Transferência",
    from: "De",
    to: "Para",
    transfer: "Transferir",
    transferring: "Transferindo...",
    transferSuccess: "Transferência realizada com sucesso.",
    transferError: "Falha ao realizar transferência.",
    allFieldsRequired: "Todos os campos são obrigatórios.",
    transferDescriptionPlaceholder: "Ex: Transferência entre contas",
    todoListTitle: "Lista de Tarefas",
    addTodo: "Adicionar Tarefa",
    updateTask: "Atualizar Tarefa",
    addOrEditTask: "Adicionar ou editar uma tarefa...",
    enterTodo: "Digite uma nova tarefa",
    allDay: "Dia todo",
    specificTime: "Horário Específico",
    close: "Fechar",
    todos: "Tarefas",
    completed: "Concluídas",
    pending: "Pendentes",
    editTask: "Editar Tarefa",
    save: "Salvar",
    overdue: "Atrasadas",
    today: "Hoje",
    thisWeek: "Essa Semana",
    upcoming: "Próximas",
    noTasks: "Nenhuma tarefa ainda. Adicione uma para começar!",
    viewCalendar: "Ver Calendário",
    priority: "Prioridade",
    priorityLow: "Baixa",
    priorityMedium: "Média",
    priorityHigh: "Alta",
    recurrence: "Recorrência",
    recurrenceNone: "Nenhuma",
    recurrenceDaily: "Diária",
    recurrenceWeekly: "Semanal",
    recurrenceMonthly: "Mensal",
    connectGoogleCalendar: "Conectar com Google Calendar",
    fullName: "Davi Monteiro Fonseca",
    rouletteParticipants: "Participantes",
    rouletteDraw: "Sortear",
    rouletteNamesUnit: "nome(s)",
    rouletteSpinButton: "Girar a Roleta",
    rouletteSpinning: "Sorteando...",
    rouletteWinners: "Vencedor(es):",
    rouletteNamesPlaceholder: "Digite os nomes, um por linha...",
    calculatorProduct: "Produto",
    calculatorAddProduct: "Adicionar Produto",
    calculatorAddedItems: "Itens Adicionados",
    calculatorNoItems: "Nenhum item adicionado ainda.",
    calculatorRemove: "Remover",
    calculatorClearAll: "Limpar Tudo",
    calculatorSummary: "Resumo do Cálculo",
    calculatorGunpowder: "Total de Pólvora Usada",
    calculatorMoneyUsed: "Total de Dinheiro Usado",
    calculatorTotalCharge: "Total a Cobrar do Cliente",
    calculatorCommission: "Comissão (20%)",
    calculatorTotalFaction: "Total para Facção",
    calculatorWithoutPartnership: "Sem Parceria",
    calculatorWithPartnership: "Com Parceria",
    privacyPolicy: "Política de Privacidade",
    termsOfService: "Termos de Serviço",
    privacy: {
      title: "Política de Privacidade",
      introduction: "Introdução",
      introductionText: "Bem-vindo à nossa Política de Privacidade. Sua privacidade é importante para nós. Esta política explica como coletamos, usamos e protegemos suas informações quando você utiliza nosso site.",
      dataCollection: "Coleta de Dados",
      dataCollectionText: "Nós coletamos apenas as informações estritamente necessárias para o funcionamento dos recursos que você decide utilizar em nosso sistema, como e-mail e dados de sessão de usuário criptografados. Não vendemos ou usamos seus dados para rastreamento de anúncios de terceiros.",
      dataCollectionToken: "",
      dataCollectionTokenText: "",
      dataCollectionDisclaimer: "",
      dataUsage: "Uso dos Dados",
      dataUsageText: "Utilizamos suas informações de conta exclusivamente para os seguintes propósitos:",
      dataUsageImport: "Personalização: Fornecer painéis de acesso pessoal como a lista de tarefas e gestão financeira.",
      dataUsageCreate: "Autenticação: Garantir que você faça login em sua conta com segurança para manter seus dados privados longe de terceiros.",
      dataUsageDelete: "",
      dataUsagePolicy: "",
      dataSharing: "Compartilhamento de Dados",
      dataSharingText: "Nós não compartilhamos, vendemos ou alugamos suas informações pessoais com terceiros sob nenhuma circunstância.",
      security: "Segurança",
      securityText: "Tomamos medidas de segurança rigorosas para proteger suas informações. Todos os acessos são feitos através de tokens de autenticação temporários (JWT), que são transmitidos por um canal seguro e validados pelo nosso servidor. Senhas são armazenadas com algoritmos de Hash irreversíveis.",
      revokingAccess: "Exclusão de Conta",
      revokingAccessText: "Você pode solicitar a exclusão total da sua conta e dados do sistema entrando em contato conosco através da página de contato.",
      contact: "Contato",
      contactText: "Se você tiver alguma dúvida sobre esta Política de Privacidade ou precisar solicitar a exclusão da sua conta, entre em contato conosco através do formulário de contato do site."
    },
    terms: {
        title: "Termos de Serviço",
        acceptance: "Aceitação dos Termos",
        acceptanceText: "Ao acessar e utilizar nosso site e seus serviços, você aceita e concorda em estar vinculado aos termos e disposições deste acordo. Se você não concorda com algum destes termos, você não está autorizado a usar este site.",
        serviceDescription: "Descrição do Serviço",
        serviceDescriptionText: "Nosso site oferece um conjunto de ferramentas pessoais, incluindo lista de tarefas e gerenciador financeiro. Este serviço é fornecido 'como está', sem garantias de qualquer tipo.",
        userConduct: "Conduta do Usuário",
        userConductText: "Você concorda em não usar o serviço para qualquer finalidade ilegal ou proibida por estes termos. Você é responsável por toda a sua atividade em conexão com o serviço.",
        googleIntegration: "Privacidade de Dados",
        googleIntegrationText: "Ao utilizar nossos serviços, você nos confia alguns dados pessoais. Nos comprometemos a manter o sigilo de suas informações, conforme descrito na nossa Política de Privacidade.",
        liabilityLimitation: "Limitação de Responsabilidade",
        liabilityLimitationText: "Em nenhuma circunstância o proprietário deste site será responsável por quaisquer danos diretos, indiretos, incidentais, especiais ou consequenciais que resultem do uso ou da incapacidade de usar este serviço. O uso do serviço é por sua conta e risco. Não oferecemos garantia de que o serviço estará livre de erros, interrupções ou perda de dados.",
        termsModification: "Modificações nos Termos",
        termsModificationText: "Reservamo-nos o direito de modificar estes termos a qualquer momento. Aconselhamos que você revise esta página periodicamente para estar ciente de quaisquer alterações. O uso continuado do site após a publicação de alterações constituirá sua aceitação dos novos termos.",
        contact: "Contato",
        contactText: "Se você tiver dúvidas sobre estes termos, entre em contato através da nossa página de contato."
    }
  },
  en: {
    greeting: "Hello, I'm",
    description: "A backend developer with experience in creating robust services and Discord bots. Currently working as an I.T Assistant, focused on creating clean and modern solutions.",
    availableForWork: "Available for new projects",
    cleanCode: "Clean Code",
    cleanCodeDesc: "Writing maintainable, scalable, and efficient solutions.",
    modernUI: "Modern UI/UX",
    modernUIDesc: "Crafting beautiful and intuitive user experiences.",
    responsive: "Responsive",
    responsiveDesc: "Perfect execution across all devices and screen sizes.",
    viewWork: "View My Work",
    getInTouch: "Get in Touch",
    home: "Home",
    portfolio: "Portfolio",
    resume: "Resume",
    products: "Products",
    contact: "Contact",
    features: "Features",
    todoList: "To-Do List",
    financeManager: "Finances",
    calculator: "Calculator",
    urlShortener: "URL Shortener",
    roulette: "Roulette",
    login: "Login",
    register: "Register",
    logout: "Logout",
    rights: "All rights reserved.",
    contactP: "Contact Me",
    connect: "Connect With Me",
    name: "Name",
    message: "Message",
    productsAndServices: "Product & Services",
    learnMore: "Learn More",
    buyNow: "Buy Now",
    sendMessage: "Send Message",
    viewProject: "View project",
    projectsList: [
        { id: 1, title: "Discord Bot", description: "A fully customizable bot focused on moderation and security.", image: "https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/4088758/cover_image/retina_1708x683/cover-how-to-make-a-discord-bot-0afaa27d630de8c4b711f5cd5abbf01f.png", link: "/plans" }
    ],
    productList: [
        { id: 1, name: "Discover the discord bots", description: "A fully customizable bot focused on moderation and security.", image: "https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/4088758/cover_image/retina_1708x683/cover-how-to-make-a-discord-bot-0afaa27d630de8c4b711f5cd5abbf01f.png", link: "/plans" },
        { id: 2, name: "FiveM Mod Manager", description: "Manage your FiveM mods with just one click. Safely install, enable, and disable sound, RPF, and Citizens mods with automatic backups and performance optimizations.", image: "https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/270123807/original/2e13089eeeef09bbb2a04d238dce1f419b5a7268/install-gta-fivem-server-with-qbcore-linux-or-windows.png", link: "/fmm-plans" }
    ],
    downloadPDF: "Download PDF",
    personalInfo: "Personal Information",
    phone: "(62) 98608-9609",
    email: "davimf9702@gmail.com",
    knowledge: "Knowledge",
    skills: "Skills",
    attitudes: "Attitudes",
    knowledgeList: ["Information Systems", "Golang", "Java", "SQL", "I.T Infrastructure", "Data Analysis"],
    skillsList: ["Fast learner", "Great logical reasoning", "I.T Infrastructure maintenance", "Advanced English"],
    tools: "Tools",
    toolsList: ["Git", "Docker", "Linux", "Postman", "Active Directory"],
    experience: "Experience",
    experienceList: [
        { title: "I.T Assistant", company: "New Line Tecnologia Em Segurança Ltda", link: "https://newlineseguranca.com.br/", period: "November 2025 - Present", description: "Direct involvement in tech support, infrastructure maintenance, Active Directory, and continuous network monitoring." },
        { title: "I.T Intern", company: "New Line Tecnologia Em Segurança Ltda", link: "https://newlineseguranca.com.br/", period: "August 2023 - October 2025", description: "Experience with networks, computer assembly and maintenance, and I.T infrastructure assistance." },
        { title: "Security Alarm and Camera Monitor", company: "Safety House - Security Services LTDA", link: "https://safetyhouse.com.br/", period: "October 2021 - March 2022", description: "Monitored security alarms and cameras during night shifts." }
    ],
    education: "Education",
    educationList: [
        { course: "Information Systems (Bachelor's)", institution: "Federal Institute of Goiás, Goiânia", link: "https://www.ifg.edu.br/", period: "August 2025 - Present", description: "Focused on software development, information management, and technological infrastructure." },
        { course: "Computer Science", institution: "Federal Institute of Goiás, Anápolis", link: "https://www.ifg.edu.br/", period: "February 2020 - July 2025", description: "Studied Operational Research, Algorithms, Data Structures, and Machine Learning." }
    ],
    manager: "Manager",
    calculatorTitle: "OCEANIA CALC",
    itemCategory: "Item Category",
    selectCategory: "Select a Category",
    farm: "Farm",
    weapons: "Weapons",
    ammunition: "Ammunition",
    drugs: "Drugs",
    contraband: "Contraband",
    illegalServices: "Illegal Services",
    item: "Item",
    quantity: "Quantity",
    totalWithPartnership: "Total with Partnership",
    totalWithoutPartnership: "Total without Partnership",
    unitPriceWithPartnership: "Unit Price (with Partnership)",
    unitPriceWithoutPartnership: "Unit Price (without Partnership)",
    plans: "Plans",
    discordBotPlans: "Discord Bot Plans",
    fivemFactionPlans: "FiveM Faction Plans",
    monthly: "Monthly",
    annually: "Annually",
    subscribe: "Subscribe",
    month: "month",
    year: "year",
    quarterly: "Quarterly",
    lifetime: "Lifetime",
    annualDiscount: "Save 16% with the annual plan!",
    fmmModManagerPlans: "FiveM Mod Manager Plans",
    discordPlans: [
        { title: "Basic", price: 35, features: ["logs", "verification", "security", "moderation", "limited_customization", "paid_features"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=01bac1298ea84b9ea952483a553811ec", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=52e56a46d88345418fe1472f0c443e1d" } },
        { title: "Intermediate", price: 50, features: ["all_basic", "vip", "five_new_features", "advanced_security", "hour_counting"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=59aab9185a0e4ca4be5334bfabd8dd6d", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=352c67ff541b492fb3126d3164928057" } },
        { title: "Advanced", price: 70, features: ["all_intermediate", "unlimited_features", "full_customization", "large_servers", "priority_support", "proactive_monitoring"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=47804a73dbed428bb9cec0852384e45c", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=60abafc09b384dee87ea6a0504bdd8cc" } }
    ],
    fivemPlans: [
        { title: "Base", price: 35, features: ["basic_features", "sell_logs", "production_logs", "sets"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=01bac1298ea84b9ea952483a553811ec", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=52e56a46d88345418fe1472f0c443e1d" } },
        { title: "Intermediate", price: 50, features: ["all_base", "financial_panel", "report_system"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=59aab9185a0e4ca4be5334bfabd8dd6d", annually: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=352c67ff541b492fb3126d3164928057" } },
        { title: "Advanced", price: 70, features: ["all_intermediate_fivem", "full_customization_fivem", "free_new_features", "priority_support_fivem"], paymentLinks: { monthly: "https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=47804a73dbed428bb9cec0852384e45c", annually: "https://www.mercadopag.com.br/subscriptions/checkout?preapproval_plan_id=60abafc09b384dee87ea6a0504bdd8cc" } }
    ],
    planFeatures: {
        discord: { logs: "Log modules", verification: "Entry verification", security: "Security modules", moderation: "Moderation", limited_customization: "Limited customization", paid_features: "New features paid separately", all_basic: "Everything from the Basic plan", vip: "VIP systems", five_new_features: "Up to 5 new features included", advanced_security: "Advanced security systems", hour_counting: "Hour counting system", all_intermediate: "Everything from the Intermediate plan", unlimited_features: "Unlimited new features", full_customization: "Fully customizable bot", large_servers: "Prepared for LARGE servers", priority_support: "Priority support", proactive_monitoring: "Proactive performance monitoring" },
        fivem: { basic_features: "Base plan features", sell_logs: "Sell logs", production_logs: "Production logs", sets: "Sets", all_base: "Everything from the Base plan", financial_panel: "Financial panel", report_system: "Reporting system", all_intermediate_fivem: "Everything from the Intermediate plan", full_customization_fivem: "100% customization", free_new_features: "Free new features", priority_support_fivem: "Priority support" }
    },
    fmmPlans: [
        { title: "Basic", prices: { monthly: 15, quarterly: 40, lifetime: 80 }, features: ["fmm_sound_mods", "fmm_rpf_mods", "fmm_one_click", "fmm_backup", "fmm_basic_support"], paymentLinks: { monthly: "#", quarterly: "#", lifetime: "#" } },
        { title: "Pro", prices: { monthly: 35, quarterly: 100, lifetime: 200 }, features: ["fmm_all_basic", "fmm_citizens", "fmm_citizens_extras", "fmm_performance", "fmm_advanced_logs", "fmm_priority_support"], paymentLinks: { monthly: "#", quarterly: "#", lifetime: "#" } }
    ],
    fmmPlanFeatures: {
        fmm_sound_mods: "Sound mod management",
        fmm_rpf_mods: "RPF mod management",
        fmm_one_click: "Enable/disable mods with 1 click",
        fmm_backup: "Automatic backup before installations",
        fmm_basic_support: "Basic support",
        fmm_all_basic: "Everything from the Basic plan",
        fmm_citizens: "Citizens management",
        fmm_citizens_extras: "CitizenExtras support",
        fmm_performance: "Windows performance optimizations",
        fmm_advanced_logs: "Advanced logs and full history",
        fmm_priority_support: "Priority support"
    },
    urlShortenerTitle: "URL Shortener",
    urlShortenerPlaceholder: "Enter URL to shorten",
    urlShortenerButton: "Shorten",
    urlShortenerLoading: "Shortening...",
    urlShortenerResult: "Shortened URL:",
    urlShortenerError: "An error occurred. Please try again.",
    urlShortenerEnterUrl: "Please enter a URL.",
    financeManagerTitle: "Finance Manager",
    addTransaction: "Add Transaction",
    transactionDescription: "Description",
    amount: "Amount",
    category: "Category",
    type: "Type",
    income: "Income",
    expense: "Expense",
    bank: "Bank",
    date: "Date",
    add: "Add",
    totalBalance: "Total Balance",
    banks: "Banks",
    addBank: "Add Bank",
    bankName: "Bank Name",
    initialBalance: "Initial Balance",
    recentTransactions: "Recent Transactions",
    edit: "Edit",
    delete: "Delete",
    update: "Update",
    cancel: "Cancel",
    confirm: "Confirm",
    confirmDelete: "Are you sure you want to delete this transaction?",
    confirmDeleteBank: "Are you sure you want to delete this bank? All associated transactions will be lost.",
    expenseByCategory: "Expenses by Category",
    expenseByType: "Expenses by Type",
    pix: "Pix",
    card: "Card",
    futureExpenses: "Future Expenses",
    paymentMonth: "Payment Month",
    pay: "Pay",
    selectBankToPay: "Select bank to pay",
    makeTransfer: "Make Transfer",
    from: "From",
    to: "To",
    transfer: "Transfer",
    transferring: "Transferring...",
    transferSuccess: "Transfer completed successfully.",
    transferError: "Failed to complete transfer.",
    allFieldsRequired: "All fields are required.",
    transferDescriptionPlaceholder: "Ex: Transfer between accounts",
    todoListTitle: "To-Do List",
    addTodo: "Add Task",
    updateTask: "Update Task",
    addOrEditTask: "Add or edit a task...",
    enterTodo: "Enter a new todo",
    allDay: "All Day",
    specificTime: "Specific Time",
    close: "Close",
    todos: "Todos",
    completed: "Completed",
    pending: "Pending",
    editTask: "Edit Task",
    save: "Save",
    overdue: "Overdue",
    today: "Today",
    thisWeek: "This Week",
    upcoming: "Upcoming",
    noTasks: "No tasks yet. Add one to get started!",
    viewCalendar: "View Calendar",
    priority: "Priority",
    priorityLow: "Low",
    priorityMedium: "Medium",
    priorityHigh: "High",
    recurrence: "Recurrence",
    recurrenceNone: "None",
    recurrenceDaily: "Daily",
    recurrenceWeekly: "Weekly",
    recurrenceMonthly: "Monthly",
    connectGoogleCalendar: "Connect with Google Calendar",
    fullName: "Davi Monteiro Fonseca",
    rouletteParticipants: "Participants",
    rouletteDraw: "Draw",
    rouletteNamesUnit: "name(s)",
    rouletteSpinButton: "Spin the Wheel",
    rouletteSpinning: "Drawing...",
    rouletteWinners: "Winner(s):",
    rouletteNamesPlaceholder: "Enter names, one per line...",
    calculatorProduct: "Product",
    calculatorAddProduct: "Add Product",
    calculatorAddedItems: "Added Items",
    calculatorNoItems: "No items added yet.",
    calculatorRemove: "Remove",
    calculatorClearAll: "Clear All",
    calculatorSummary: "Calculation Summary",
    calculatorGunpowder: "Total Gunpowder Used",
    calculatorMoneyUsed: "Total Money Used",
    calculatorTotalCharge: "Total to Charge Client",
    calculatorCommission: "Commission (20%)",
    calculatorTotalFaction: "Total for Faction",
    calculatorWithoutPartnership: "Without Partnership",
    calculatorWithPartnership: "With Partnership",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    privacy: {
        title: "Privacy Policy",
        introduction: "Introduction",
        introductionText: "Welcome to our Privacy Policy. Your privacy is important to us. This policy explains how we collect, use, and protect your information when you use our website.",
        dataCollection: "Data Collection",
        dataCollectionText: "We only collect the information strictly necessary for the operation of the features you choose to use in our system, such as email and encrypted user session data. We do not sell or use your data for third-party ad tracking.",
        dataCollectionToken: "",
        dataCollectionTokenText: "",
        dataCollectionDisclaimer: "",
        dataUsage: "Data Usage",
        dataUsageText: "We use your account information exclusively for the following purposes:",
        dataUsageImport: "Personalization: To provide access to personal dashboards like your to-do list and financial management.",
        dataUsageCreate: "Authentication: To ensure you can securely log into your account and keep your private data away from third parties.",
        dataUsageDelete: "",
        dataUsagePolicy: "",
        dataSharing: "Data Sharing",
        dataSharingText: "We do not share, sell, or rent your personal information with third parties under any circumstances.",
        security: "Security",
        securityText: "We take rigorous security measures to protect your information. All access is handled via temporary authentication tokens (JWT) transmitted over a secure channel and validated by our server. Passwords are stored using irreversible hashing algorithms.",
        revokingAccess: "Account Deletion",
        revokingAccessText: "You can request the complete deletion of your account and data from our systems by contacting us through the contact page.",
        contact: "Contact",
        contactText: "If you have any questions about this Privacy Policy or need to request the deletion of your account, please contact us through the site's contact form."
    },
    terms: {
        title: "Terms of Service",
        acceptance: "Acceptance of Terms",
        acceptanceText: "By accessing and using our website and its services, you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to any of these terms, you are not authorized to use this site.",
        serviceDescription: "Service Description",
        serviceDescriptionText: "Our site offers a suite of personal tools, including a to-do list and a financial manager. This service is provided 'as is', without warranties of any kind.",
        userConduct: "User Conduct",
        userConductText: "You agree not to use the service for any purpose that is illegal or prohibited by these terms. You are responsible for all of your activity in connection with the service.",
        googleIntegration: "Data Privacy",
        googleIntegrationText: "By using our services, you entrust us with certain personal data. We are committed to maintaining the confidentiality of your information, as described in our Privacy Policy.",
        liabilityLimitation: "Limitation of Liability",
        liabilityLimitationText: "Under no circumstances shall the owner of this site be liable for any direct, indirect, incidental, special, or consequential damages that result from the use of or inability to use this service. Your use of the service is at your sole risk. We do not warrant that the service will be error-free, uninterrupted, or free of data loss.",
        termsModification: "Modifications to Terms",
        termsModificationText: "We reserve the right to modify these terms at any time. We advise you to review this page periodically for any changes. Your continued use of the site after the posting of changes will constitute your acceptance of such changes.",
        contact: "Contact",
        contactText: "If you have any questions about these terms, please contact us through our contact page."
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');
  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
